### ISSUE TITLE
Can't create group with next-release

### ISSUE THREAD

**Issue by Thatoo** [wheelybird/ldap-user-manager#100]
![image](https://user-images.githubusercontent.com/464782/119354051-e570d400-bca3-11eb-8bfa-3ce2471e1116.png)

The RFC2307BIS schema appears to be available but it's not working.

However, if I reinstall an ldap server without the RFC2307BIS schema but the nis schema then it can creates groups but I didn"t test further as I don't want to get trouble later without the RFC2307BIS schema...

**Comment by wheelybird** [comment]
That's fixed already - I'll push the changes when I'm able.

**Comment by wheelybird** [comment]
I've pushed the changes to the next_release branch and updated the container image.

**Comment by Thatoo** [comment]
it works now.
