### ISSUE TITLE
Add multiple values for attribute vie WEB UI

### ISSUE THREAD

**Issue by nicx** [wheelybird/ldap-user-manager#104]
I was wondering if it is possible to add multiple fields for the same LDAP attribute in the WebUI. In my case I want to add multiple "mailAlias" attributes to a user, but when using LDAP_ACCOUNT_ADDITIONAL_ATTRIBUTES I can only add it once.

When I set it to `mailAlias:Email Alias 1:,mailAlias:Email Alias 2:,mailAlias:Email Alias 3` I can only see the last field `Email Alias 3` in the WebUI.

Is this somehow possible? If not: Could it be implemented? :)

**Comment by wheelybird** [comment]
Hi.  I understand what you're after.  It's not currently possible but I'll see if I can implement multi-field attributes in the next release.

**Comment by wheelybird** [comment]
This is incorporated into the latest release (v1.8).

**Comment by lukasstevens** [comment]
Many thanks!
