### ISSUE TITLE
Syntax error on upgrading v1.6 to v1.7

### ISSUE THREAD

**Issue by Michuelnik** [wheelybird/ldap-user-manager#108]
**Check the debugging logs**
Enabled LDAP_DEBUG and LDAP_VERBOSE_CONNECTION_LOGS.
Nothing there, just the logged HTTP Request returning 200.

**Version**
`image: wheelybird/ldap-user-manager:v1.7`

**Describe the bug**
When opening LUM in the browser like it's worked on v1.6 before, the browser only shows this error, nothing else:
` Parse error: syntax error, unexpected token "if" in /opt/ldap_user_manager/includes/config.inc.php on line 37`

**Comment by wheelybird** [comment]
Thanks!  I've pushed a new version of v1.7 with the fix.  Could you `pull wheelybird/ldap-user-manager:v1.7` and try again?

**Comment by Michuelnik** [comment]
This works now, thank you!
