### ISSUE TITLE
Example setup file

### ISSUE THREAD

**Issue by LindezaGrey** [wheelybird/ldap-user-manager#11]
Hey there,

is it possible to add an example configuration? For example a docker-compose file with the mentioned osixia/openldap image? I have a hard time getting the setup to work, with lots of php errors and such.

Thanks and best regards

**Comment by wheelybird** [comment]
Here's a quick guide on how to set up an LDAP container and then manage it with the user manager:

**Step one** - set up LDAP.   We use bind-mounted volumes to make the directory persistent.  I'm putting them in /opt/docker/openldap but of course you can change this.   

I'm enabling RFC2307BIS_SCHEMA as this allows the memberOf module, which is really useful.

Note that we're doing this without TLS enabled.  This is just for testing; you'll certainly want to enable TLS for any production systems.  See https://github.com/osixia/docker-openldap#tls for more information.

```
docker pull osixia/openldap:latest
docker run \
             --name openldap \
             -e LDAP_ORGANISATION=example \
             -e LDAP_DOMAIN=example.org \
             -e LDAP_ADMIN_PASSWORD=somepassword \
             -e LDAP_CONFIG_PASSWORD=somepassword \
             -e LDAP_RFC2307BIS_SCHEMA=true \
             -e LDAP_REMOVE_CONFIG_AFTER_SETUP=true \
             -e LDAP_TLS=false \
             -p 389:389 \
             -p 636:636 \
             --volume /opt/docker/openldap/var_lib_ldap:/var/lib/ldap \
             --volume /opt/docker/openldap/etc_ldap_slapd.d:/etc/ldap/slapd.d \
             osixia/openldap:latest --loglevel debug

```
When it says 'slapd starting' you can Ctrl+C to kill the container.  Now you've now got LDAP initialised you can bring it up in the future with the following:

```
docker stop openldap && docker rm openldap
docker run \
             --detach \
             --restart unless-stopped \
             --name openldap \
             -p 389:389 \
             -p 636:636 \
             -e LDAP_TLS=false \
             --volume /opt/docker/openldap/var_lib_ldap:/var/lib/ldap \
             --volume /opt/docker/openldap/etc_ldap_slapd.d:/etc/ldap/slapd.d \
             --hostname=localhost \
             --env KEEP_EXISTING_CONFIG=true \
             osixia/openldap
```

(but don't forget to enable TLS once you've got this working).

**Step two** - run the user manager.

```
docker pull wheelybird/ldap-user-manager

docker run \
           --detach \
           --restart unless-stopped \
           --name=lum \
           -p 80:80 \
           -p 443:443 \
           -e SERVER_HOSTNAME=localhost \
           -e LDAP_URI=ldap://172.17.0.1 \
           -e LDAP_BASE_DN=dc=example,dc=org \
           -e LDAP_ADMINS_GROUP=admins \
           -e LDAP_ADMIN_BIND_DN="cn=admin,dc=example,dc=org" \
           -e LDAP_ADMIN_BIND_PWD=somepassword \
           -e NO_HTTPS=TRUE \
           wheelybird/ldap-user-manager
```

Again, TLS is disabled (NO_HTTPS=TRUE) as this is a test setup.  The LDAP_URI points to the docker0 bridge interface in Linux.  If you're not using Linux then you'll need to change this accordingly.

Now in a browser go to http://localhost/setup   
Log in with the LDAP_ADMIN_PASSWORD we set up earlier (somepassword).  Go through the wizard to add the required LDAP records and add an initial administrative account.  Once that's done, you're all set up.

Hope this helps.

**Comment by LindezaGrey** [comment]
Wow thank you that was some good and fast help! The part that caused the problem for me was that the openldap container created a very basic structure. In your example that gets removed with "LDAP_REMOVE_CONFIG_AFTER_SETUP=true" That was the part that i was missing. Also i did not have "RFC2307BIS_SCHEMA" enabled.

**Comment by wheelybird** [comment]
Glad you got it working.   You don't need RFC2307BIS_SCHEMA for the user manager to work, but it's a useful module as some systems that authenticate against LDAP don't allow you to limit access via groups but do allow you use filters, hence you can use a filter like `(&(uid=example-user)(memberof=cn=admins,ou=groups,dc=example,dc=org))`
