### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by fundies** [wheelybird/ldap-user-manager#110]
I suspect it's the wrong user but I'm not sure what user it's using by default and how to change it as the debug logs don't list what user it tries.

Failed to bind to ldap.lab.local as dc=alchemytechnology,dc=com with password ****: Invalid credentials, referer: https://10.100.45.158:8080/setup/

**Comment by fundies** [comment]
putting -e "LDAP_ADMIN_BIND_DN=uid=diradmin,dc=alchemytechnology,dc=com" allows me to log in to the setup page but I still cannot login via the login page.

```ldap.lab.local:443 10.100.45.28 - - [11/Aug/2021:16:53:32 +0000] "POST /log_in/index.php HTTP/1.1" 302 327 "https://10.100.45.158:8080/log_in/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"
[Wed Aug 11 16:53:32.178222 2021] [php:notice] [pid 29] [client 10.100.45.28:52688]  Session: orf_cookie wasn't sent by the client., referer: https://10.100.45.158:8080/log_in/index.php
ldap.lab.local:443 10.100.45.28 - - [11/Aug/2021:16:53:32 +0000] "GET /log_in/index.php?invalid HTTP/1.1" 200 976 "https://10.100.45.158:8080/log_in/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"```

**Comment by wheelybird** [comment]
Did you complete the setup process and create an admin group and user?

**Comment by fundies** [comment]
Yep. It just isn't sending or getting the cookie. Not sure why

**Comment by wheelybird** [comment]
Have you got Nginx in front of the user manager?

**Comment by jonathanmmm** [comment]
Seems to be the same, as for us:
https://github.com/wheelybird/ldap-user-manager/issues/109

**Comment by wheelybird** [comment]
Unfortunately I still haven't been able to replicate this issue, even when adding Nginx in front of the user manager.  Can you all confirm that you can log into `/setup` with bind DN credentials, but the problem is when you log into the user manager itself with the new admin user you created during setup?

**Comment by fundies** [comment]
I was unable to fix this and decided to use another tool so I will close this out.
