### ISSUE TITLE
Mandatory Fields Setting

### ISSUE THREAD

**Issue by lily148** [wheelybird/ldap-user-manager#121]
Hi @wheelybird , thanks for sure a good docker application.

May I know is there a way to set the attribute or extra attribute as mandatory fields?
I don't see it in the setting.

For my case, if I leave the "First name" and "Last name" blank then system will return an invalid syntax error.
The error will show as below:
     Invalid syntax
givenname: value #0 invalid per syntax

**Comment by cyberb** [comment]
Why first and last name are required then, is it possible to make it skip them if they are not set?

**Comment by cyberb** [comment]
Looks like there is a lot of code to use first and last name, so they are required currently, made this PR to make them required in the UI so users know what is wrong if they forget to fill the fields: https://github.com/wheelybird/ldap-user-manager/pull/190

**Comment by cyberb** [comment]
![image](https://user-images.githubusercontent.com/885528/221374241-be412de7-926b-462c-9d23-dc07573f5819.png)

**Comment by wheelybird** [comment]
I've merged the PR and updated the Docker images.  Thanks for your help!
