### ISSUE TITLE
Warning: Undefined variable $initialise_group in /opt/ldap_user_manager/account_manager/show_group.php on line 91

### ISSUE THREAD

**Issue by pookey** [wheelybird/ldap-user-manager#123]
**Version**
running 1.7 and latest, issue appears in both

**Describe the bug**
When adding a user to a group, via the 'groups' section - I get this error:

Warning: Undefined variable $initialise_group in /opt/ldap_user_manager/account_manager/show_group.php on line 91

Attached is a log with LDAP debugging turned on.

[ldap-bug1.log](https://github.com/wheelybird/ldap-user-manager/files/7288791/ldap-bug1.log)

**Comment by wheelybird** [comment]
Cheers.  I was aware of this one - it'll be fixed in the next update, which should be within the next couple of weeks.
