### ISSUE TITLE
cannot remove someone from group if they are the last person in that group

### ISSUE THREAD

**Issue by pookey** [wheelybird/ldap-user-manager#124]
**Version**
1.7 and latest, but appear to be affected

**Describe the bug**
When I try to remove the final member from a group, no frontend error is reported - however if navigate back to  look at that group, the user is still a member of that group.

In my example attached,  'tacacshelpdesk' contains just 'Curtis'.   Removing them via the page:  account_manager/show_group.php?group_name=tacacshelpdesk

the related errors appear to be:

 ```
res_errno: 65, res_error: <object class 'groupOfUniqueNames' requires attribute 'uniqueMember'>, res_matched: <>
 ldap_free_request (origid 9, msgid 9)
 ldap_parse_result
 ldap_msgfree
 ldap_err2string
 ldap_err2string
 [Tue Oct 05 19:48:49.850721 2021] [php:notice] [pid 31] [client 2.121.69.75:58071]  Couldn't remove 'uid=wcurtis,ou=people,dc=my-domain,dc=com' from tacacshelpdesk: Object       class violation, referer: https://88.80.185.224:8443/account_manager/show_group.php?group_name=tacacshelpdesk
```
[ldap-bug2.log](https://github.com/wheelybird/ldap-user-manager/files/7288838/ldap-bug2.log)

**Comment by wheelybird** [comment]
This is down to the fact that a groupOfUniqueNames can't be empty.  There always needs to be at least one entry, so the LDAP server won't delete that final member.  For now you'd need to delete the group.  I'd need to think of a way to allow an empty group, though off the top of my head I can't think of a way.
