### ISSUE TITLE
Add attribute like "EmployeeID" to LUM Interface

### ISSUE THREAD

**Issue by nboukerma** [wheelybird/ldap-user-manager#125]
Hi, 

We have added some attributes to our LDAP like : 

- Job TITLE 
- EmployeeID
- Manager 

How can we see/fill/update these fields in the PHP LDAP User Manager interface ?

**Comment by wheelybird** [comment]
Hello.  You can add additional attributes as explained here:  https://github.com/wheelybird/ldap-user-manager#extra-objectclasses-and-attributes
You'll almost certainly need to add the objectClass(es) for the attributes too.

I've just noticed an error in the explanation of the format for this; it should read `attribute1:label1:default_value1,attribute2:label2:default_value2`

So you might have LDAP_ACCOUNT_ADDITIONAL_ATTRIBUTES set to `jobTitle:Job title,employeeID:Employee ID,manager:Line manager`
