### ISSUE TITLE
HTTP support issue - cookies are always secure

### ISSUE THREAD

**Issue by pookey** [wheelybird/ldap-user-manager#126]
**Version**
master

**Describe the bug**
the DEFAULT_COOKIE_OPTIONS are set to 'secure'.  
includes/web_functions.inc.php
```
$DEFAULT_COOKIE_OPTIONS = array( 'expires' => time()+(60 * $SESSION_TIMEOUT),
                                 'path' => $SERVER_PATH,
                                 'domain' => '',
                                 'secure' => TRUE,
                                 'samesite' => 'strict'
                               );
```

You have a env var that allows toggling of HTTPS, but if you move to HTTP (and do not have a HTTPS reverse proxy) then the cookie is never returned by the browser as it's marked as secure only.

One potential fix would be to toggle this based on your condition above for HTTPS detection.

**Comment by wheelybird** [comment]
Thanks for this. Good idea about HTTPS detection too.  I'll get that fixed as soon as I can.
