### ISSUE TITLE
 Warning: Undefined array key "mail" in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323

### ISSUE THREAD

**Issue by mnxamoto** [wheelybird/ldap-user-manager#127]
Version: 1.7

Describe the bug:
Most likely after smbldap-tools set up its structure in ldap, this error message began to appear on the Users tab. 

Warning: Undefined array key "mail" in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323
Warning: Trying to access array offset on value of type null in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323
Warning: Undefined array key "mail" in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323
Warning: Trying to access array offset on value of type null in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323
Warning: Undefined array key "givenname" in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323
Warning: Trying to access array offset on value of type null in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323
Warning: Undefined array key "mail" in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323
Warning: Trying to access array offset on value of type null in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 323

**Comment by wheelybird** [comment]
Cheers.  I can see the issue - it'll be fixed in the next release.
