### ISSUE TITLE
Nothing Happens During Setup

### ISSUE THREAD

**Issue by tuaris** [wheelybird/ldap-user-manager#128]
**Check the debugging logs**
Debug logs do not show any login or connection errors

**Version**
master 37076f8, running on FreeBSD 13.0, PHP 8.0, and Apache 2.4

**Describe the bug**
Accessing http://lum.mydomain.dev/setup redirects me to http://lum.mydomain.dev/setup/index.php?unauthorised.  No errors are displayed on the screen or in the log. This is a new LDAP server on a new Ubuntu 20.04 instance.

![image](https://user-images.githubusercontent.com/5660265/145536411-f34490c6-4ef9-45fa-a382-e479aea9edc3.png)

The error log shows (ldap_debug and ldap_verbose_connection_logs is set to TRUE) :
```
[Fri Dec 10 02:37:37.828812 2021] [php:notice] [pid 59003] [client 192.168.99.2:11400]  Attempting to bind to ldap://master.prod.mydomain.net as cn=admin,dc=prod,dc=mydomain,dc=net, referer: http://lum.mydomain.dev/setup/
[Fri Dec 10 02:37:38.014596 2021] [php:notice] [pid 59003] [client 192.168.99.2:11400]  Bound successfully as cn=admin,dc=prod,dc=mydomain,dc=net, referer: http://lum.mydomain.dev/setup/
[Fri Dec 10 02:37:38.014635 2021] [php:notice] [pid 59003] [client 192.168.99.2:11400]  Initial setup: opening another LDAP connection to test authentication as cn=admin,dc=prod,dc=mydomain,dc=net., referer: http://lum.mydomain.dev/setup/
[Fri Dec 10 02:37:38.200879 2021] [php:notice] [pid 59003] [client 192.168.99.2:11400]  Attempting to bind to ldap://master.prod.mydomain.net as cn=admin,dc=prod,dc=mydomain,dc=net, referer: http://lum.mydomain.dev/setup/
[Fri Dec 10 02:37:38.386880 2021] [php:notice] [pid 59003] [client 192.168.99.2:11400]  Bound successfully as cn=admin,dc=prod,dc=mydomain,dc=net, referer: http://lum.mydomain.dev/setup/
[Fri Dec 10 02:37:38.479865 2021] [php:notice] [pid 59003] [client 192.168.99.2:11400]  Initial setup: able to authenticate as cn=admin,dc=prod,dc=mydomain,dc=net., referer: http://lum.mydomain.dev/setup/
```

**Comment by zeo101** [comment]
I have the same error.
Have you been able to figure out a solution?

**Comment by wheelybird** [comment]
No, I've had no time lately to work on this project.  I should be able to dedicated time to it near the start of next month.

**Comment by zeo101** [comment]
Probably related to the cookie issue in #122.
Got it working using image `wheelybird/ldap-user-manager:oldcookies`.
I couldn't get Firefox, Edge or Brave working with `wheelybird/ldap-user-manager:latest`.

**Comment by bsnuggs1** [comment]
@zeo101 - Thanks for mentioning that,

> Probably related to the cookie issue in #122. Got it working using image `wheelybird/ldap-user-manager:oldcookies`. I couldn't get Firefox, Edge or Brave working with `wheelybird/ldap-user-manager:latest`.

@zeo101 - Thanks for mentioning that, this solved my issue!
