### ISSUE TITLE
When changing First Name and Last Name displayName doesn't change

### ISSUE THREAD

**Issue by herculesbl9** [wheelybird/ldap-user-manager#129]
Hello!

First of all I would like to say congrats for a wonderful app! It has been incredibly easy to use especially for people with little or no experience with LDAP.
This is more of a feauture request than a bug, that is why I did not use that form. When creating a new user and adding their details via LUM, the displayName attribute is automatically updated. However, when one of the said fields is modified, the displayName attribute remains unchanged.

Would it be possible to automatically change the displayName attribute as well?

Thanks in advance

**Comment by wheelybird** [comment]
Hi.  Glad you like the user manager.  I'll look into the displayName change for the next release.

**Comment by wheelybird** [comment]
Hi.  I'm working on the next release and revisiting this.  The displayName isn't by default one of the editable attributes.  Did you mean Common Name (cn)?

**Comment by herculesbl9** [comment]
Hello! When enrolling a user to LDAP using LUM, the displayName attribute automatically returns the user's "First Name"+" "+"Last Name". When changing the First Name and Last name attributes the display name attribute does not seem to change.
The displayName attribute itself isn't by default editable, as you indicated, but is set by default in the background.
I do not, however, know if this is done by the LDAP server or LUM.

I hope the way I put it makes sense, let me know if you would like me to elaborate even further, or if what I am suggesting is not even possible, I'm afraid that my knowledge of LDAP is quite limited.

**Comment by wheelybird** [comment]
Hi.  Yes, the displayName is set by the application when the account is created.  I think this is a legacy action as displayName isn't a required attribute for inetOrgPerson.  The issue with automatically updating it when the account is modified is that some people might want their displayName to be unrelated to their actual name.  I think it might be better to remove the code that automatically sets displayName.   If you want it to be set then you can set`LDAP_ACCOUNT_ADDITIONAL_ATTRIBUTES=displayname` which will then show that attribute on the account management pages.   Does that sound reasonable?

**Comment by herculesbl9** [comment]
Hello! Sure thing, it is simpler that way.
I will set up my installation as you suggest, thank you for the assistance.

**Comment by wheelybird** [comment]
This is incorporated into the latest release (v1.8).

**Comment by xcojonny** [comment]
Hej there, 

is it possible to prefill the field like USERNAME_FORMAT={first_name} {last_name} ?

**Comment by wheelybird** [comment]
@xcojonny sure, that should work.  Information on the available macros is here:  https://github.com/wheelybird/ldap-user-manager#username-format

**Comment by xcojonny** [comment]
Hej, 

I tried the following:
- LDAP_ACCOUNT_ADDITIONAL_ATTRIBUTES=displayname:Display Name:{first_name} {last_name}

leads to the following
<img width="541" alt="Bildschirmfoto 2023-12-08 um 11 06 27" src="https://github.com/wheelybird/ldap-user-manager/assets/22481238/e094860c-8c98-49ee-95cc-42532e7198c0">

And the following leads to:
- LDAP_ACCOUNT_ADDITIONAL_ATTRIBUTES='displayname:Display Name:{first_name} {last_name}'
<img width="506" alt="Bildschirmfoto 2023-12-08 um 11 11 33" src="https://github.com/wheelybird/ldap-user-manager/assets/22481238/7cce8c76-2be4-4c5c-9599-7c880471405a">


any ideas what I'm doing wrong?

**Comment by wheelybird** [comment]
Oh, no you can't use macros in LDAP_ACCOUNT_ADDITIONAL_ATTRIBUTES.  Sorry for the confusion.  To be honest I think it'd be a fair bit of work to get that working.

**Comment by xcojonny** [comment]
ah, ok. Good to know, that I'm doing nothing wrong :D
