### ISSUE TITLE
Unauthorized Error

### ISSUE THREAD

**Issue by adrha** [wheelybird/ldap-user-manager#13]
I have a strange issue.
If i try to login with the admin-password i'm redirected to /unauthorized.
The password is right, if i enter it wrong, it tells me i entered a wrong password.

My compose-file:

wheelybird:
    image: wheelybird/ldap-user-manager:latest
    container_name: ajs-ldapweb
    restart: always
    ports:
      - "8008:80"
      - "8009:443"
    environment:
      LDAP_URI: "ldap://172.17.0.1"
      LDAP_BASE_DN: "dc=myrealdc,dc=ch"
      LDAP_REQUIRE_STARTTLS: "FALSE"
      LDAP_ADMINS_GROUP: "admins"
      LDAP_ADMIN_BIND_DN: "cn=admin,dc=myrealdc,dc=ch"
      LDAP_ADMIN_BIND_PWD: ${LDAP_ADMIN_PW?error}
      EMAIL_DOMAIN: "myrealmaildomain"
      NO_HTTPS: "TRUE"

What can i do? Log is not telling me more than that the STARTTLS-connection could not be initiated.

Note: The LDAP-Server works well for 3 services like gitlab, nextcloud and wekan, so i guess it's not an issue from the OpenLdap-Server

**Comment by wheelybird** [comment]
Could you send some logs regardless?  Also try `${LDAP_ADMIN_WD:?error}` just to check for an empty variable as well as an unset one.

**Comment by wheelybird** [comment]
I've pushed a new Docker image with more debugging information.  Try using `wheelybird/ldap-user-manager:ldap-debug` and pass `-e LDAP_DEBUG=TRUE` to the container when it starts.  Be aware that this will show the bind password in the logs.  Hopefully it'll help you sort out your issue.

**Comment by adrha** [comment]
Wow nice thank you for your help!

Well the environment-variable can't be empty. Otherwise docker-compose will not build and throw an error. (because of the ?error tag).

I've just pulled the debug-tagged image, when i look at the "docker-logs", there is nothing different than yesterday i guess.
Do i have to check the log in a specific file inside the container?

Actual log from now: (myrealdc is changed):
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.224.3. Set the 'ServerName' directive globally to suppress this message
[Fri May 01 17:11:46.265126 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.0.33 OpenSSL/1.0.2q configured -- resuming normal operations
[Fri May 01 17:11:46.265191 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.1.10:8008 192.168.1.51 - - [01/May/2020:17:11:59 +0000] "GET /setup/index.php HTTP/1.1" 200 857 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
[Fri May 01 17:12:09.198080 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager -  -  Failed to start STARTTLS connection to ldap://172.17.0.1, referer: http://192.168.1.10:8008/setup/index.php
[Fri May 01 17:12:09.199662 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager -  -  Bound to ldap://172.17.0.1 as cn=admin,dc=myrealdc,dc=ch, referer: http://192.168.1.10:8008/setup/index.php
[Fri May 01 17:12:09.199706 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager -  -  Initial setup: opening another LDAP connection to test authentication as cn=admin,dc=myrealdc,dc=ch., referer: http://192.168.1.10:8008/setup/index.php
[Fri May 01 17:12:09.205699 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager -  -  Failed to start STARTTLS connection to ldap://172.17.0.1, referer: http://192.168.1.10:8008/setup/index.php
[Fri May 01 17:12:09.206860 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager -  -  Bound to ldap://172.17.0.1 as cn=admin,dc=myrealdc,dc=ch, referer: http://192.168.1.10:8008/setup/index.php
[Fri May 01 17:12:09.207557 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager -  -  Initial setup: able to authenticate as cn=admin,dc=myrealdc,dc=ch., referer: http://192.168.1.10:8008/setup/index.php
192.168.1.10:8008 192.168.1.51 - - [01/May/2020:17:12:09 +0000] "POST /setup/index.php HTTP/1.1" 302 442 "http://192.168.1.10:8008/setup/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.10:8008 192.168.1.51 - - [01/May/2020:17:12:09 +0000] "GET /setup/run_checks.php HTTP/1.1" 302 291 "http://192.168.1.10:8008/setup/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.10:8008 192.168.1.51 - - [01/May/2020:17:12:09 +0000] "GET /setup/index.php?unauthorised HTTP/1.1" 200 856 "http://192.168.1.10:8008/setup/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"

**Comment by wheelybird** [comment]
The extra debugging shows that the LDAP authentication is fine. This could 
be a cookie issue. Could you try using a different browser (e.g. Firefox) 
and see if that makes a difference?

**Comment by adrha** [comment]
I tried already with Chrome / Edge / IE (i gave him a try) and Firefox.
No success. Always redirected to unauthorized...


> The extra debugging shows that the LDAP authentication is fine. This could be a cookie issue. Could you try using a different browser (e.g. Firefox) and see if that makes a difference?
> […](#)
> On 1 May 2020 18:21:49 Adrian ***@***.***> wrote: Wow nice thank you for your help! Well the environment-variable can't be empty. Otherwise docker-compose will not build and throw an error. (because of the ?error tag). I've just pulled the debug-tagged image, when i look at the "docker-logs", there is nothing different than yesterday i guess. Do i have to check the log in a specific file inside the container?Actual log from now: (myrealdc is changed): AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.224.3. Set the 'ServerName' directive globally to suppress this message [Fri May 01 17:11:46.265126 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.0.33 OpenSSL/1.0.2q configured -- resuming normal operations [Fri May 01 17:11:46.265191 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND' 192.168.1.10:8008 192.168.1.51 - - [01/May/2020:17:11:59 +0000] "GET /setup/index.php HTTP/1.1" 200 857 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" [Fri May 01 17:12:09.198080 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager - - Failed to start STARTTLS connection to ldap://172.17.0.1, referer: http://192.168.1.10:8008/setup/index.php [Fri May 01 17:12:09.199662 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager - - Bound to ldap://172.17.0.1 as cn=admin,dc=myrealdc,dc=ch, referer: http://192.168.1.10:8008/setup/index.php [Fri May 01 17:12:09.199706 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager - - Initial setup: opening another LDAP connection to test authentication as cn=admin,dc=myrealdc,dc=ch., referer: http://192.168.1.10:8008/setup/index.php [Fri May 01 17:12:09.205699 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager - - Failed to start STARTTLS connection to ldap://172.17.0.1, referer: http://192.168.1.10:8008/setup/index.php [Fri May 01 17:12:09.206860 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager - - Bound to ldap://172.17.0.1 as cn=admin,dc=myrealdc,dc=ch, referer: http://192.168.1.10:8008/setup/index.php [Fri May 01 17:12:09.207557 2020] [:error] [pid 18] [client 192.168.1.51:51908] 2020-05-01 17:12:09 - LDAP manager - - Initial setup: able to authenticate as cn=admin,dc=myrealdc,dc=ch., referer: http://192.168.1.10:8008/setup/index.php 192.168.1.10:8008 192.168.1.51 - - [01/May/2020:17:12:09 +0000] "POST /setup/index.php HTTP/1.1" 302 442 "http://192.168.1.10:8008/setup/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" 192.168.1.10:8008 192.168.1.51 - - [01/May/2020:17:12:09 +0000] "GET /setup/run_checks.php HTTP/1.1" 302 291 "http://192.168.1.10:8008/setup/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" 192.168.1.10:8008 192.168.1.51 - - [01/May/2020:17:12:09 +0000] "GET /setup/index.php?unauthorised HTTP/1.1" 200 856 "http://192.168.1.10:8008/setup/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wheelybird** [comment]
I've pushed a new image with increased logging verbosity.  Please try image `wheelybird/ldap-user-manager:ldap-debug` with `LDAP_DEBUG=TRUE` and ` SESSION_DEBUG=TRUE` enable.  The logs should then give us an idea of why this isn't working for you.

**Comment by adrha** [comment]
Nice man thanks for the push!

Now the log is telling me more interesting things!
Is the IS_SETUP_ADMIN variable a variable from your application?


[Mon May 04 09:58:37.274983 2020] [:error] [pid 21] [client 192.168.1.51:49900]  Session: orf_cookie wasn't sent by the client.
[Mon May 04 09:58:45.682352 2020] [:error] [pid 20] [client 192.168.1.51:49901]  Session: orf_cookie wasn't sent by the client., referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.704975 2020] [:error] [pid 20] [client 192.168.1.51:49901] 2020-05-04 09:58:45 - LDAP manager -  -  Failed to start STARTTLS connection to ldap://172.17.0.1, referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.705919 2020] [:error] [pid 20] [client 192.168.1.51:49901] 2020-05-04 09:58:45 - LDAP manager -  -  Bound to ldap://172.17.0.1 as cn=admin,dc=myrealdc,dc=ch, referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.705961 2020] [:error] [pid 20] [client 192.168.1.51:49901] 2020-05-04 09:58:45 - LDAP manager -  -  Initial setup: opening another LDAP connection to test authentication as cn=admin,dc=myrealdc,dc=ch., referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.709402 2020] [:error] [pid 20] [client 192.168.1.51:49901] 2020-05-04 09:58:45 - LDAP manager -  -  Failed to start STARTTLS connection to ldap://172.17.0.1, referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.711014 2020] [:error] [pid 20] [client 192.168.1.51:49901] 2020-05-04 09:58:45 - LDAP manager -  -  Bound to ldap://172.17.0.1 as cn=admin,dc=myrealdc,dc=ch, referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.711602 2020] [:error] [pid 20] [client 192.168.1.51:49901] 2020-05-04 09:58:45 - LDAP manager -  -  Initial setup: able to authenticate as cn=admin,dc=myrealdc,dc=ch., referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.711854 2020] [:error] [pid 20] [client 192.168.1.51:49901]  Setup session: sent setup_cookie to the client., referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.727713 2020] [:error] [pid 20] [client 192.168.1.51:49901]  Session: orf_cookie wasn't sent by the client., referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.729273 2020] [:error] [pid 20] [client 192.168.1.51:49901]  Session: setup_cookie wasn't sent by the client., referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.729309 2020] [:error] [pid 20] [client 192.168.1.51:49901]  Session: UNAUTHORISED: page security level is 'setup' but IS_SETUP_ADMIN isn't TRUE, referer: http://192.168.1.10:8008/setup/
[Mon May 04 09:58:45.748492 2020] [:error] [pid 20] [client 192.168.1.51:49901]  Session: orf_cookie wasn't sent by the client., referer: http://192.168.1.10:8008/setup/

**Comment by wheelybird** [comment]
Yes, it's an internal variable.   The logs show that you authenticate, the authentication cookie is sent to your browser and then the next page is loaded and the cookie is missing.  So for some reason your browser isn't storing the cookie.
Maybe if you enable the developer console on your browser you might get some information on why the cookie's missing.   My first thought is that there's a time difference between where the container's running and your browser - if your browser's significantly behind then it will immediate expire due to the login timeout setting.

**Comment by adrha** [comment]
Okay i've checked the time of the container. There was a difference from 2hrs.
Container was running on UTC-Time, host-system and client were both running in central-europe time.
I've fixed this but it had no impact to the error.

In the Cookie-tab of the page-debugger is no cookie shown, that arrived from the webserver.
Is it mandatory to run the setup on port 80/443 for some reasons?

I will try to figure out why no cookie arrived from the server and will let you know if i have found something.

**Comment by adrha** [comment]
Hey i just saw while searching for the error that in the setup-section in the index.php file, that you are closing a div more than you are opening. (Line 50).
This might not be the error but just saw while debugging in the browser ^^

https://github.com/wheelybird/ldap-user-manager/blob/f9edeb39b058a10a078a0e8526226033b01ccc0a/www/setup/index.php#L50

**Comment by wheelybird** [comment]
Hi.  This seems to be an issue with the way browsers on Macs accept cookies.  I don't have a Mac to test this with.  Could you try a new image: `wheelybird/ldap-user-manager:mac` - I've changed the way the cookies are set and hopefully it'll work.
I've also sorted out the rouge div in that image - thanks for spotting it.

**Comment by adrha** [comment]
Nice one! It works no! Even i'm not an Apple-user, it solved the problem.
But now i'm having the same errors as described in the other issue: https://github.com/wheelybird/ldap-user-manager/issues/12

I will try to find out what's wrong as you said it is ldap-scheme related.

**Comment by wheelybird** [comment]
It is a schema issue.  The code originally worked with the NIS schema 
(the default in osixia/openldap) as well as the BIS schema, but 
somewhere down the line that got broken.  I've got a fix for that which 
I'll push after work today.

**Comment by wheelybird** [comment]
I've made some fixes that ought to solve the issue.  Please try the latest image (either `wheelybird/ldap-user-manager:latest` or `wheelybird/ldap-user-manager:v1.0`).
The issue was that you're using the default schema provided by `osixia/openldap` - the NIS schema.  The user manager was supposed to be able to use that schema but at some point the code changed and broke that.  To use the NIS schema you need to pass `LDAP_USES_NIS_SCHEMA=TRUE` as a variable.

Alternatively you can use the BIS schema with OpenLDAP - with `osixia/openldap` you need to pass `LDAP_RFC2307BIS_SCHEMA=true` when you initialise LDAP.  This is generally a preferable schema.

Hopefully this will solve your problem.

**Comment by adrha** [comment]
Nice man this worked!

Thanks for your suport!
