### ISSUE TITLE
Is it possible to change the schema used to the simpler inetOrgPerson  only?

### ISSUE THREAD

**Issue by xpufx** [wheelybird/ldap-user-manager#130]
We do not use ldap in a unix environment and as such do not need the posixGroup related fields uidnumber,gidnumber,homedirectory and loginshell. It's a simple authentication store for us. Since we have existing users in the directory, this is causing a lot of errors and we will never need these fields. It's making the simple account edit page more confusing than necessary for our users.

**Comment by LordFelius** [comment]
Hi, you can have a look at [my fork](https://github.com/LordFelius/ldap-user-manager). I'm using inetOrgPerson and nameOfGroups schema so I modified it. It's not fully tested but works fine with my LDAP. If you're interested, let me know if any bug happens.

**Comment by xpufx** [comment]
@LordFelius Thank you. I have started working on an authentik idP setup. It looks like I might not need to manually manage my LDAP directory anymore.
