### ISSUE TITLE
Last name initial not replaced correctly

### ISSUE THREAD

**Issue by dubit0** [wheelybird/ldap-user-manager#138]
When looking through the code, I realized that the following is probably a mistake: The placeholder `{first_name_initial}` is replaced by the first letter of the *last* name.

https://github.com/wheelybird/ldap-user-manager/blob/45f834ff2e56af9ec0f2359c9899fa8dc2c9600f/www/includes/web_functions.inc.php#L440

**Comment by wheelybird** [comment]
Oops.  :/

**Comment by wheelybird** [comment]
This is fixed in the latest release (v1.8).
