### ISSUE TITLE
using on windows IIS with PHP

### ISSUE THREAD

**Issue by baha00** [wheelybird/ldap-user-manager#14]
is it possible to use it on windows IIS with php enabled?

**Comment by wheelybird** [comment]
Hi.  This was really designed to be packaged inside a Docker container.  I have no experience of IIS at all, so I really couldn't say if it would work in a Windows environment and I don't know how portable PHP is across different OSes.
Saying that, I can't think why it wouldn't.  It picks up a lot of settings from environmental variables, so I would as long as those could be set for IIS/PHP to pick up then I expect it's feasible.

**Comment by baha00** [comment]
Hi wheelybird, it kinda works... just took over php files, but where are ldap  settings
![image](https://user-images.githubusercontent.com/17033913/80840934-4d1a3400-8bf6-11ea-98c6-020ea94dafc5.png)

**Comment by wheelybird** [comment]
You need to set them as environmental variables that can be picked up by PHP.  I'm not sure how you do that in Windows/IIS.
