### ISSUE TITLE
Possible without Docker ?

### ISSUE THREAD

**Issue by julpec** [wheelybird/ldap-user-manager#140]
Hello
I would have liked to use the service without using docker because it seems very complicated. Moreover, on my machine, I already have a web server running. So I just need to create a new virtual host and I won't have to worry about ports, reverse proxy or even installing Docker.
So, is it possible with a basic apache web server ?

**Comment by wheelybird** [comment]
Hi.  Yes it is.  As configuration is passed in via environmental variables you'll need to pass those to Apache somehow.  If you're on Debian/Ubuntu you could put them in /etc/apache2/envvars.  Alternatively you could place them in the VirtualHost section using "SetEnv VARIABLE_NAME variable_value".
Aside from that all you need to do is set the directory root and the default index extensions:
```DocumentRoot /path/to/ldap-user-manager/www
 DirectoryIndex index.php index.html
```

**Comment by julpec** [comment]
Great! It works like a charm, thanks.
It was quite difficult to get it to work with the RFC because it is not implemented by default in slapd under Debian but I got it to work.

**Comment by Justinzobel** [comment]
Is it possible to have instructions for this in the README and have lum take the variables from a configuration file instead?
