### ISSUE TITLE
REQUEST: Option to silence and/or disable TLS connection

### ISSUE THREAD

**Issue by gdevenyi** [wheelybird/ldap-user-manager#145]
Every time I connect to my localhost LDAP server ldap-user-manager logs a error because TLS doesn't work. I think some rework to silence any warnings if doing localhost connections would be easiest here.

**Comment by wheelybird** [comment]
Is this the "Failed to start STARTTLS connection to xxx" message?

**Comment by gdevenyi** [comment]
Yes, sorry, I failed to make that clear.
