### ISSUE TITLE
Feature Request: Add uploading of jpegPhoto

### ISSUE THREAD

**Issue by gdevenyi** [wheelybird/ldap-user-manager#148]
iNetorgPerson has a jpegPhoto attribute which is used by other services to provide a headshot, it would be nice if uploading such binaries into LDAP would be possible (ideally by the user, see #147 )

**Comment by DrDoug88** [comment]
This feature is only available for the account manager to change. Can you make it available for the actual user to edit?

Thanks for your work btw.
