### ISSUE TITLE
Cannot add more than one user to group

### ISSUE THREAD

**Issue by jonathanwerle** [wheelybird/ldap-user-manager#152]
**Check the debugging logs**
-> Done. Can't find anything suspicious.

**Version / Startscript**
```bash
#!/bin/bash
docker run \
        --detach \
        --network=ldap \
        --name=lum_prod \
        -p 5476:80 \
        -p 5477:443 \
        -e "SERVER_HOSTNAME=user.example.com" \
        -e "LDAP_URI=ldap://ldap.example.com" \
        -e "LDAP_BASE_DN=dc=example,dc=com" \
        -e "LDAP_REQUIRE_STARTTLS=true" \
        -e "LDAP_ADMINS_GROUP=admins" \
        -e "LDAP_ADMIN_BIND_DN=cn=admin,dc=example,dc=com" \
        -e "LDAP_ADMIN_BIND_PWD=TOPSECRET" \
        -e "LDAP_IGNORE_CERT_ERRORS=true" \
        -e "USERNAME_FORMAT={first_name}{last_name}" \
        -e "SITE_NAME=ExampleCom User Manager" \
        -e "LDAP_DEBUG=true" \
        -e "SESSION_DEBUG=true" \
        wheelybird/ldap-user-manager:v1.8
```

**Describe the bug**
I can't add more than one user to a group. I have some old data which i have imported via ldif and cmd. In old groups are sometimes multiple users, but i can't add more users. I have created a testgroup using LDAP User Manager, where i can't add more than one user.

Thanks for your work on this amazing project and thanks in advance for your help!

**Comment by jonathanwerle** [comment]
Now it's getting interesting: I found out, that while changing a group membership via the groups interface doesn't work (as described above), it works via the users' interface.

Any idea why one works and the other one doesn't?

**Comment by nadtoka** [comment]
@jonathanwerle I think I am having the same issue... well I cannot add users to groups

When create a group and add user during creation process it works fine BUT when I go to GROUPS and trying to modify it by adding some new members it does not work. Without any errors....


Any update on this?

**Comment by jonathanwerle** [comment]
@nadtoka unfortunately i haven't found a solution, yet! Could you try what i have described [above](https://github.com/wheelybird/ldap-user-manager/issues/152#issuecomment-1105839552)?
-> Adding a user to groups via the users' interface

**Comment by wheelybird** [comment]
I think this is fixed now.  Could you try with the new image?  `docker pull wheelybird/ldap-user-manager:v1.8`

**Comment by jonathanwerle** [comment]
@wheelybird thank you very much. I can confirm: this is fixed now! Your work is much appreciated!
