### ISSUE TITLE
Request Account Validation Image Broken

### ISSUE THREAD

**Issue by DrDoug88** [wheelybird/ldap-user-manager#157]
**Version**
v1.8 via Docker, i.e. wheelybird/ldap-user-manager:v1.8

**Describe the bug**
The Non-human detection image shows a broken image, as indicated in the following screenshot:

![image](https://user-images.githubusercontent.com/80653458/165896618-72c99ee9-cfb3-405c-91bd-165fc25fe040.png)

This is behind a reverse proxy (Traefik). However, I also tried it directly on local ip, with both HTTP and HTTPS, but the issue remained.  I also tried it on many different browsers (Chrome, Edge, Firefox, Vivaldi), but the issue was the same on all of them.

This issue renders the entire account request function unusable. 

Here are the logs:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 5.6.7.8. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 5.6.7.8. Set the 'ServerName' directive globally to suppress this message
[Fri Apr 29 01:39:25.164843 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/8.1.5 OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Apr 29 01:39:25.164883 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Fri Apr 29 01:39:38.068629 2022] [php:notice] [pid 25] [client 1.2.3.4:55472]  Session: orf_cookie wasn't sent by the client.
[Fri Apr 29 01:39:38.068654 2022] [php:notice] [pid 25] [client 1.2.3.4:55472]  Session: The session had timed-out (over 10 mins idle).
openldap.example.com:443 1.2.3.4 - - [29/Apr/2022:01:39:38 -0500] "GET / HTTP/1.1" 200 2587 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.147 Safari/537.36"
[Fri Apr 29 01:39:46.570714 2022] [php:notice] [pid 23] [client 1.2.3.4:55486]  Session: orf_cookie wasn't sent by the client., referer: https://ldapmanager.example.com/
[Fri Apr 29 01:39:46.570740 2022] [php:notice] [pid 23] [client 1.2.3.4:55486]  Session: The session had timed-out (over 10 mins idle)., referer: https://ldapmanager.example.com/
openldap.example.com:443 1.2.3.4 - - [29/Apr/2022:01:39:46 -0500] "GET /request_account/ HTTP/1.1" 200 3373 "https://ldapmanager.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.147 Safari/537.36"
openldap.example.com:443 1.2.3.4 - - [29/Apr/2022:01:39:46 -0500] "GET /request_account/human.php HTTP/1.1" 200 5078 "https://ldapmanager.example.com/request_account/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.147 Safari/537.36"

Thank you for all of your work on this project.

**Comment by wheelybird** [comment]
Thanks for reporting this.  It should be fixed now thanks to the PR @ilarrain submitted.   You should do a `docker pull wheelybird/ldap-user-manager:v1.8` to get the latest version.

**Comment by DrDoug88** [comment]
Wow. Impressive turnaround. Pulled the new image and it works great! Thank you!!!
