### ISSUE TITLE
Error when trying to reset a user's password

### ISSUE THREAD

**Issue by herculesbl9** [wheelybird/ldap-user-manager#163]
**Version**
v1.8 in docker

**Describe the bug**
Hello!

Once again, congrats for the amazing update, the new features have proven very useful. While using the app, I encountered an error when trying to reset a users password. I am pasting the PHP error below:

<pre><code>
Fatal error: Uncaught TypeError: str_replace(): Argument #2 ($replace) must be of type string when argument #1 ($search) is a string in 
/opt/ldap_user_manager/includes/mail_functions.inc.php:33 Stack trace: #0 
/opt/ldap_user_manager/includes/mail_functions.inc.php(33): str_replace('{first_name}', Array, 'You've been set...') #1 
/opt/ldap_user_manager/account_manager/show_user.php(187): parse_mail_text('You've been set...', 'password...', 'username', 
Array, Array) #2 {main} thrown in /opt/ldap_user_manager/includes/mail_functions.inc.phpon line 33--
</code></pre>

I have only changed the user's username and password above, to protect their identity.

Please let me know if any additional info is needed.
Thanks in advance

**Comment by wheelybird** [comment]
Thanks.  There's another report of this, so something must be up.  Have you got anything set for `RESET_PASSWORD_EMAIL_SUBJECT` or `RESET_PASSWORD_EMAIL_BODY`?

**Comment by herculesbl9** [comment]
Just double checked this, just to be sure, nothing seems to be set on these two.

**Comment by the-working-rene** [comment]
I encountered the same Issue. I quickly fixed it for me by changing lines 187 to 192 in www/account_manager/show_user.php to

```php
      $mail_body = parse_mail_text($new_account_mail_body, $password, $account_identifier, $givenname[0], $sn[0]);
      $mail_subject = parse_mail_text($new_account_mail_subject, $password, $account_identifier, $givenname[0], $sn[0]);
      $sent_email = send_email($mail[0],"$givenname[0] $sn[0]",$mail_subject,$mail_body);
      if ($sent_email) {
        $sent_email_message .= "  An email sent to $mail[0].";
      }
```

That is, changing `$mail`, `$givenname` and `$sn` to `$mail[0]`, `$givenname[0]` and `$sn[0]`

I'm not sure, if this affects any other part of the code or if it only works in certain cases. But for me, it works now.

**Comment by wheelybird** [comment]
Could you give wheelybird/ldap-user-manager:reset_fix a go?  Hopefully that'll fix it.

**Comment by the-working-rene** [comment]
When trying to login, now I get this Message: 
 
``` Parse error: syntax error, unexpected token "{" in /opt/ldap_user_manager/account_manager/index.php on line 65```

**Comment by wheelybird** [comment]
That's fixed.  If you `pull wheelybird/ldap-user-manager:reset_fix` and try again it should hopefully work.

**Comment by the-working-rene** [comment]
The mail now was sent succefully, but still, the informational message after that fails:

 
![grafik](https://user-images.githubusercontent.com/88379617/171363265-5abdaf94-9749-4cad-bc81-26ec7210c717.png)

**Comment by BrianLycett-Which** [comment]
Hmm.  Weird, I didn't get that when I tested it.  Let me look at it some more.

**Comment by wheelybird** [comment]
This is fixed and pushed to `wheelybird/ldap-user-manager:v1.8` and `wheelybird/ldap-user-manager:latest`.

**Comment by herculesbl9** [comment]
I am really sorry for the delay, just checked everything out today, everything seems to be resolved.
