### ISSUE TITLE
Warning if email is missing

### ISSUE THREAD

**Issue by dr-waterstorm** [wheelybird/ldap-user-manager#166]
**Version**
1.8

**Describe the bug**
I setup the latest version of LDAP User Manager. It connected perfectly fine to the LDAP and can read all users as well as groups. However some of the users in our LDAP do not have an email set.

This results in one warning message on the GUI per user without an email set:

```
Warning: Undefined array key "mail" in /opt/ldap_user_manager/account_manager/index.php on line 69
```

![image](https://user-images.githubusercontent.com/11409264/170951017-77ab3d71-1eff-469c-99ad-c713908bf4ae.png)

I could not find anything related to this in the issue tracker here. I assume that somehow the LDAP user manager assumes that every account needs an email and if it does not exists it shows an error on the page. We're mostly using it for login on Ubuntu servers where we didn't need any email addresses.

Until now I've only used phpLDAPadmin which does not complain about this. However I'm still using the old 1.x version which looks very oldschool and I'd like to switch over to your pretty nice looking app :)

**Comment by wheelybird** [comment]
Hi.  Thanks for reporting this.  Yes, if you've enabled sending an email on account creation then the code assumes there's an email address.  That'll be fixed in the next update.

**Comment by dr-waterstorm** [comment]
This is fixed, thank you very much!
