### ISSUE TITLE
Cannot connect to ldaps (TLS: peer cert untrusted or revoked (0x42))

### ISSUE THREAD

**Issue by Shakespeare2000** [wheelybird/ldap-user-manager#172]
**Version**
Version: v1.8

**Describe the bug**
I can't connect to LDAP ([Bitnami Docker OpenLDAP](https://github.com/bitnami/bitnami-docker-openldap)) via ldaps on port 1636.
Connecting to the same LDAP server with Apache Directory Studio does work (and shows the valid certificate of the LDAP server).

I can't explain why, but the suggestion from https://github.com/docker-mailserver/docker-mailserver/issues/2340 (`apt install libldap-common`) fixes my problem. Can you add this to the Dockerfile? Or should a make a PR?

Log:
> ldap_sasl_bind_s
> ldap_sasl_bind
> ldap_new_socket: 10
> ldap_prepare_socket: 10
> connect success
> TLS: peer cert untrusted or revoked (0x42)
> TLS: can't connect: (unknown error code).
> ldap_err2string

**Comment by wheelybird** [comment]
Thanks for reporting this.  It's no problem to add this into the Dockerfile.  If you could raise a PR that'd be great.

**Comment by wheelybird** [comment]
Cheers!  I've merged the PR and pushed a new version of the container.  User `docker pull wheelybird/ldap-user-manager:v1.8` to get it.
