### ISSUE TITLE
Account generation from request account link is broken

### ISSUE THREAD

**Issue by gdevenyi** [wheelybird/ldap-user-manager#176]
**Version**
Master running on PHP8

**Describe the bug**

Following a link from a request account email, the following error shows up in the logs:
```
Uncaught Error: Cannot unset string offsets in /opt/ldap-user-manager/www/account_manager/new_user.php:106
```

**Comment by gdevenyi** [comment]
Looks like removing the `unset` lines after solves the issue, based on the other commit, the code was changed to save a string instead of an array element so the unset is no longer needed.

**Comment by wheelybird** [comment]
Hi.  Thanks for reporting that.  I'll get that fixed.

**Comment by wheelybird** [comment]
That should be fixed now with the latest version (wheelybird/ldap-user-manager:v1.9).
