### ISSUE TITLE
Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by mbay-ODW** [wheelybird/ldap-user-manager#194]
**Version**
Using Master branch with latest tag:

```yaml
ldap-user-manager:
    image: wheelybird/ldap-user-manager:latest
```

During the setup process I got various deprecation warnings.

![image](https://user-images.githubusercontent.com/58465677/226374064-80757660-5856-4cc7-8dab-92a2a561e234.png)

**Comment by jpvlerbe** [comment]
I can confirm the issue and I additionally have:
`Warning: Cannot modify header information - headers already sent by (output started at /opt/ldap_user_manager/setup/run_checks.php:38) in /opt/ldap_user_manager/includes/web_functions.inc.php on line 176`

**Comment by wheelybird** [comment]
This should be fixed now.  You'll need to run `docker pull wheelybird/ldap-user-manager:latest` to pick up the changes.
