### ISSUE TITLE
setup seems to hang

### ISSUE THREAD

**Issue by jpvlerbe** [wheelybird/ldap-user-manager#195]
I want to start a new openldap instance for that I have started a docker-compose with `osixia/openldap:1.5.0` and `wheelybird/ldap-user-manager:v1.10` images.

I can successfully reach the setup page and login with the admin password set in my docker-compose file. It gives me a list of items to create. When I hit the "Next" button I get an empty page. That is empty apart from the warnings shown in #194

**Comment by husamwise** [comment]
this problem also appear on my new setup.

**Comment by wheelybird** [comment]
This should be fixed now.  You'll need to run `docker pull wheelybird/ldap-user-manager:v1.10` to pick up the changes.
