### ISSUE TITLE
Request: dot and/or dash /blank email warning

### ISSUE THREAD

**Issue by zer0ish** [wheelybird/ldap-user-manager#196]
Hello,

Been playing with this all day and so far I do enjoy it. It's clean and works.
During the User creation process, you enter first name, then last name, and the System username gets auto filled.
I really like this, but would like to have it be a dot "." instead of a dash "-".  It would be cool to have the ability to change it to my preference. Even with a variable I can put into my unraid container. AUTOFILL_USERNAME_DASH = true, or AUTOFILL_USERNAME_DOT= true
![image](https://user-images.githubusercontent.com/29928635/229660115-344c4b80-9518-4828-b64b-9d1a20438edd.png)
This doesn't break my ability to use it, but since I already create all my users with first.lastname it would streamline it allot.

Also has a warning when creating a user without an email:
![image](https://user-images.githubusercontent.com/29928635/229660074-7a697632-2936-46d5-808f-992895665d82.png)

I'm sure this is intentional to warn that admin forgot to put an email. Would be nice to have a cleaner warning.
Something like this but for the email:
![image](https://user-images.githubusercontent.com/29928635/229660410-faab52f4-c22a-45ab-8b39-947669182209.png)

Loving it so far. Thanks for the work.

**Comment by wheelybird** [comment]
Hi.  You can change the auto-generated username format with this setting:  https://github.com/wheelybird/ldap-user-manager#username-format e.g. `USERNAME_FORMAT={first_name}.{last_name}`.
Do you know which version you're using at the moment?  I thought the blank email issue was sorted out a while back.

**Comment by zer0ish** [comment]
I'll give that a try for the . instead of -.

I'm running :latest from docker hub 
docker pull wheelybird/ldap-user-manager:latest

**Comment by zer0ish** [comment]
Wow no idea how I missed that variable to change the dash to a dot. I read over that part at least 4 times looking for that.
That worked great, and thank you!
