### ISSUE TITLE
lower admin level

### ISSUE THREAD

**Issue by nische** [wheelybird/ldap-user-manager#201]
Hi, 
im not the LDAP expert and my be there is a way to fix my need out of the box or on the LDAP-Server side. 

The highest Service level is the admin group. They can handel everything (Groups and users).

I want a group like useradmin. A users in this goup can manage normal users (no member of admin or useradmin) to put them in other groups (not admin). 

Is something like that possible? 

BR, 
NiSche

**Comment by wheelybird** [comment]
Hi.  I'm afraid that that's not possible with ldap-user-manager - it's designed for a simpler use case than you described.  There might be other LDAP admin tools that allow this, but I'm not familiar enough with them to say which ones can.

**Comment by nische** [comment]
Thanks a lot for your fast reply 😊

Okay. Thats what I thought because it is a complexer use case indeed. 

Maybe I find time to implement a feature in the future 😂
