### ISSUE TITLE
Request - Password reset link in email

### ISSUE THREAD

**Issue by zer0ish** [wheelybird/ldap-user-manager#205]
Hello,

Would it be possible to be able to change the info sent in the email on account creation?
I use [self-service-password ](https://hub.docker.com/r/ltbproject/self-service-password/) for my users to reset their passwords and recover them. I would like to be able to edit the URL that gets sent in the email. I don't want them to have access to the lum portal so being able to change it would be great.

I'd be ok with even mapping out the location of the email template in docker if that could be provided. Not sure where this is in the docker container. 

or maybe be able to remove the "/change_password" part of the link to only have the main url I want to use.

Thanks.

**Comment by wheelybird** [comment]
You can change the body of the email as described here:  https://github.com/wheelybird/ldap-user-manager#sending-emails
There are several macros you can use to pass in user information into the email body.

**Comment by zer0ish** [comment]
This is great. Exactly what I was looking for. Thank you!
