### ISSUE TITLE
Password hash and minimum strength.

### ISSUE THREAD

**Issue by CHBMB** [wheelybird/ldap-user-manager#21]
First off, I love this project!

I've been trying to implement LDAP into a home setting, and been wrestling with phpLDAPadmin, Apache Directory Services, LDAP Account Manager and LDIF files until I came across this beauty, so thank you for the hard work!

I was wondering a couple of things about the password policy, firstly, whether we could choose to use perhaps something other than `md5` to hash with and secondly whether the password policy could be relaxed or optional.

The first point I think might be worth considering as pretty sure md5 is no longer deemed to be a secure password hashing algorithm and it might be worth changing to something like SSHA?

The second point I know seems a bit unintuitive since I've just mentioned using a more secure hash/salt algorithm but I'll outline my use case.  I'm currently using LDAP on my home network as a backend for a number of services, some of my family users just can't cope with complex passwords, so I'd like the ability to relax the password strength for them.

Thanks again, and might I suggest adding a donation/paypal link, as I'd quite happily send a donation for a few beers for your work.

**Comment by wheelybird** [comment]
Thanks for the compliments.  :D
There's a reason I used MD5, but I honestly can't remember what it was.  It's a good idea to be able to select your hash though.  And explicitly turning off the password check should be fine (though of course some LDAP servers have the password policy module enabled anyway).
I'll work on that and push a test image as soon as I can.

**Comment by CHBMB** [comment]
That's awesome, now about that beer I owe you mate....

**Comment by wheelybird** [comment]
Hi.  I've pushed a branch: https://github.com/wheelybird/ldap-user-manager/tree/hashing
This introduces the variables `PASSWORD_HASH` (MD5, SHA, SMD5, SSHA or CRYPT; default is SSHA) and `ACCEPT_WEAK_PASSWORDS` (TRUE or FALSE).  There's a docker image: wheelybird/ldap-user-manager:hashing
I've only done very basic tests on the different hashes, so I can't guarantee that they'll work properly.  Still, give it a go and let me know if it's working for you.

**Comment by CHBMB** [comment]
I did some limited testing late last night, and can confirm the `ACCEPT_WEAK_PASSWORDS` variable worked fine.

I can confirm the `PASSWORD_HASH` parameter meant that passwords were encoded with `SSHA` but when I changed it to another parameter, like `MD5` or `CRYPT` they were still being encoded with `SSHA` 

Now I'll be the first to admit it was very late at night and I think I need to do some more testing with a fresh LDAP install which I'll do hopefully tonight, I'm not a dev, but can't see any reason why it shouldn't work when I looked at the code though. (I did this just to check I was defining the variables correctly).

Will report back hopefully later tonight.

Thanks very much for working on this.

**Comment by wheelybird** [comment]
I found the issue - it was a incorrect variable name in the code that checks for env variables.  I've fixed that and updated the image on docker hub.

**Comment by CHBMB** [comment]
Awesome, will test again later.  Told you I didn't understand php! :smile:

**Comment by CHBMB** [comment]
Tried out all the different `PASSWORD_HASH` options and can confirm they're all working as expected.  :+1:

**Comment by wheelybird** [comment]
Great.  Thanks a lot for checking that out.  I'll merge it into master.
