### ISSUE TITLE
Using apache proxy configuration leads to wrong http URLs

### ISSUE THREAD

**Issue by aglavic** [wheelybird/ldap-user-manager#210]
**Version**
1.10

**Describe the bug**
I'm running the docker image on a server with apache2 configured to forward our sub-domain to http://localhost:9080/ and can access the setup page through that domain. However, when I submit the form the request is send to "http://localhost:9080/..." instead of "https://my.domain.org/...".
I can manually change the URL and then the site loads normally. Some of the Links work fine but the initial configuration and creation of users etc. always falls back to localhost.

I did configure the SERVER_HOSTNAME environment variable to use my.domain.org but that seems to be ignored. The php code in question seems to access $_SERVER["HTTP_HOST"] to generate the URLs.

Any tips how I have to configure the setup to work with my virtual host correctly?

(Maybe this is irrelevant, but I'm using the http only configuration with ldap-user-manager as the apache proxy already provides https with the right certificats.)

**Comment by wheelybird** [comment]
Hi.  I can't really help on configurations outside of the user-manager, but it sounds like you haven't set ProxyPassReverse in your own Apache config.  https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by aglavic** [comment]
Thanks for the quick response. I did set the reverse proxy, but didn't work.

I changed the lum configuration to use HTTPS and then it worked normally.
