### ISSUE TITLE
Can I also change the SAMBA PASSWORD (sambaNTPassword)?

### ISSUE THREAD

**Issue by OneTop4458** [wheelybird/ldap-user-manager#216]
hello
I am currently using LDAP with SAMBA.

Programs like ldapadmin.exe support changing the SAMBA PASSWORD.

Is it possible to change SAMBA PASSWORD(sambaNTPassword) like ldap user password with this program?

**Comment by wheelybird** [comment]
Hi.  In theory this is possible with the OpenLDAP smbk5pwd overlay.  The overlay will cause the OpenLDAP server to update sambaNTPassword each time the user password is updated, so it's not ldap-user-manager that's updating it.
This does mean that you need to install smbk5pwd on you OpenLDAP server though.
