### ISSUE TITLE
Incorrect URL in the email sent to admin for ACCOUNT_REQUESTS

### ISSUE THREAD

**Issue by K-J-VV** [wheelybird/ldap-user-manager#221]
When users request an account, the following email is sent to the ACCOUNT_REQUESTS_EMAIL address:

`A request for an LDAP account has been sent:
First name: John
Last name: Smith
Email: johnsmith@example.com
Notes:

n/a

[Create this account.](https://ldapusermanager.org/account_manager/new_user.php?account_request&first_name=John&last_name=Smith&email=johnsmith@example.com)`

The problem is the URL used in the 'Create this account' hyperlink always sets the base URL as `https://ldapusermanager.org` . The full url is, `
https://ldapusermanager.org/account_manager/new_user.php?account_request&first_name=John&last_name=Smith&email=johnsmith@example.com` . However, in my instance (and likely others) the url we are using for LUM/ldap-user-manager is some self-hosted website. For example, `https://lum.example.com` .

Would it be possible to add an environment variable (e.g., ACCOUNT_REQUESTS_URL) that would change the URL generated from these requests to the custom domain of the user's choice? The way it is currently set, the generated hyperlink seems to be generally useless?

**Comment by wheelybird** [comment]
Hi.  You didn't include your configuration, but it sounds like you haven't set `SERVER_HOSTNAME` (see https://github.com/wheelybird/ldap-user-manager?tab=readme-ov-file#optional).

**Comment by K-J-VV** [comment]
Thank you! That was it

I did have that env variable set, but had a typo... 

much appreciated
