### ISSUE TITLE
Rejecting Valid E-mails

### ISSUE THREAD

**Issue by KPull** [wheelybird/ldap-user-manager#23]
Hey,

The application is rejecting the following e-mail address and similar:

`alice.doe@phalanx.software`

This e-mail is a valid e-mail address however the application shows an invalid e-mail error when creating an admin account during setup or while adding a user.

**Comment by wheelybird** [comment]
I can see the issue.  I'll get that fixed ASAP.

**Comment by wheelybird** [comment]
If you pull the Docker image with tag v1.1 again or use latest then that should be working now.

**Comment by KPull** [comment]
It works. Great job! Thanks a lot and keep up the good work. :)
