### ISSUE TITLE
an error occurred duraing setup

### ISSUE THREAD

**Issue by hryGithub** [wheelybird/ldap-user-manager#24]
![image](https://user-images.githubusercontent.com/32188410/82998763-b1d07f00-a03a-11ea-89e4-9c7e40ba9169.png)
An error occurred during setup,my ldap-server run as docker base on image osixia/openldap:1.3.0

**Comment by wheelybird** [comment]
That's really not very much to go on.  Please enable LDAP_DEBUG and check the container's logs - that should give you insight as to why this is happening.  You also neglected to say how you configured the container or which version of the container you're using.

**Comment by hryGithub** [comment]
the program couldn't create "cn=admins,ou=groups"  and "cn=everybody,ou=groups", then I create these manually,when I create admin user success, but   the user coudn't  be added to the admins group.

**Comment by wheelybird** [comment]
I can't help unless you provide more information - set LDAP_DEBUG to TRUE and paste the logs (mind that it will display passwords).  What are the settings you passed to the container?  Which version of the container image are you using?

**Comment by hryGithub** [comment]
the ldap-server image is osixia/openldap:1.3.0, and the lum image is wheelybird/ldap-user-manager:v1.1(image id :3b3e719765c1 ),

**Comment by wheelybird** [comment]
That's a start, but you *really* need to give me the settings used to launch the container and the debug-level logs.  It would also be useful to see the osixia/openldap settings.
The point I'm trying to make is that there are number of settings you can pass to the ldap-user-manager container which affect how it works, and unless I know what you set I can't begin to guess at what your issue is.

**Comment by hryGithub** [comment]
the defaut groups(admins and everybody)，should be groupOfUniqueNames，but the groupOfUniqueNames require attribute uniquemember, that's the problem
------------------------------------------ldap logs as bellow---------------
5ecf72b3 conn=1060 fd=13 ACCEPT from IP=192.168.9.249:55374 (IP=0.0.0.0:389)
5ecf72b3 conn=1060 op=0 EXT oid=1.3.6.1.4.1.1466.20037
5ecf72b3 conn=1060 op=0 STARTTLS
5ecf72b3 conn=1060 op=0 RESULT oid= err=0 text=
TLS: can't accept: No certificate was found..
5ecf72b3 conn=1060 fd=13 closed (TLS negotiation failure)
5ecf72b3 conn=1061 fd=13 ACCEPT from IP=192.168.9.249:55376 (IP=0.0.0.0:389)
5ecf72b3 conn=1061 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
5ecf72b3 conn=1061 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5ecf72b3 conn=1061 op=0 RESULT tag=97 err=0 text=
5ecf72b3 conn=1062 fd=14 ACCEPT from IP=192.168.9.249:55378 (IP=0.0.0.0:389)
5ecf72b3 conn=1062 op=0 EXT oid=1.3.6.1.4.1.1466.20037
5ecf72b3 conn=1062 op=0 STARTTLS
5ecf72b3 conn=1062 op=0 RESULT oid= err=0 text=
TLS: can't accept: No certificate was found..
5ecf72b3 conn=1062 fd=14 closed (TLS negotiation failure)
5ecf72b3 conn=1063 fd=14 ACCEPT from IP=192.168.9.249:55380 (IP=0.0.0.0:389)
5ecf72b3 conn=1063 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
5ecf72b3 conn=1063 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5ecf72b3 conn=1063 op=0 RESULT tag=97 err=0 text=
5ecf72b3 conn=1063 op=1 BIND anonymous mech=implicit ssf=0
5ecf72b3 conn=1063 op=1 BIND dn="cn=admin,dc=example,dc=org" method=128
5ecf72b3 conn=1063 op=1 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5ecf72b3 conn=1063 op=1 RESULT tag=97 err=0 text=
5ecf72b3 conn=1063 op=2 UNBIND
5ecf72b3 conn=1063 fd=14 closed
5ecf72b3 conn=1061 op=1 UNBIND
5ecf72b3 conn=1061 fd=13 closed
5ecf72b3 conn=1064 fd=13 ACCEPT from IP=192.168.9.249:55382 (IP=0.0.0.0:389)
5ecf72b3 conn=1064 op=0 EXT oid=1.3.6.1.4.1.1466.20037
5ecf72b3 conn=1064 op=0 STARTTLS
5ecf72b3 conn=1064 op=0 RESULT oid= err=0 text=
TLS: can't accept: No certificate was found..
5ecf72b3 conn=1064 fd=13 closed (TLS negotiation failure)
5ecf72b3 conn=1065 fd=13 ACCEPT from IP=192.168.9.249:55384 (IP=0.0.0.0:389)
5ecf72b3 conn=1065 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
5ecf72b3 conn=1065 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5ecf72b3 conn=1065 op=0 RESULT tag=97 err=0 text=
5ecf72b3 conn=1065 op=1 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=organizationalUnit)(ou=groups))"
5ecf72b3 <= mdb_equality_candidates: (ou) not indexed
5ecf72b3 conn=1065 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
5ecf72b3 conn=1065 op=2 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=organizationalUnit)(ou=people))"
5ecf72b3 <= mdb_equality_candidates: (ou) not indexed
5ecf72b3 conn=1065 op=2 SEARCH RESULT tag=101 err=0 nentries=1 text=
5ecf72b3 conn=1065 op=3 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=device)(cn=lastgid))"
5ecf72b3 <= mdb_equality_candidates: (cn) not indexed
5ecf72b3 conn=1065 op=3 SEARCH RESULT tag=101 err=0 nentries=1 text=
5ecf72b3 conn=1065 op=4 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=device)(cn=lastuid))"
5ecf72b3 <= mdb_equality_candidates: (cn) not indexed
5ecf72b3 conn=1065 op=4 SEARCH RESULT tag=101 err=0 nentries=1 text=
5ecf72b3 conn=1065 op=5 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=posixGroup)(cn=everybody))"
5ecf72b3 conn=1065 op=5 SEARCH RESULT tag=101 err=0 nentries=0 text=
5ecf72b3 conn=1065 op=6 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=posixGroup)(cn=admins))"
5ecf72b3 conn=1065 op=6 SEARCH RESULT tag=101 err=0 nentries=0 text=
5ecf72b3 conn=1065 op=7 UNBIND
5ecf72b3 conn=1065 fd=13 closed
5ecf72c3 conn=1066 fd=13 ACCEPT from IP=192.168.9.249:55386 (IP=0.0.0.0:389)
5ecf72c3 conn=1066 op=0 EXT oid=1.3.6.1.4.1.1466.20037
5ecf72c3 conn=1066 op=0 STARTTLS
5ecf72c3 conn=1066 op=0 RESULT oid= err=0 text=
TLS: can't accept: No certificate was found..
5ecf72c3 conn=1066 fd=13 closed (TLS negotiation failure)
5ecf72c3 conn=1067 fd=13 ACCEPT from IP=192.168.9.249:55388 (IP=0.0.0.0:389)
5ecf72c3 conn=1067 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
5ecf72c3 conn=1067 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5ecf72c3 conn=1067 op=0 RESULT tag=97 err=0 text=
5ecf72c3 conn=1067 op=1 SRCH base="ou=groups,dc=example,dc=org" scope=2 deref=0 filter="(cn=everybody,ou=groups,dc=example,dc=org)"
5ecf72c3 <= mdb_equality_candidates: (cn) not indexed
5ecf72c3 conn=1067 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
5ecf72c3 conn=1067 op=2 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=device)(cn=lastgid))"
5ecf72c3 conn=1067 op=2 SRCH attr=serialNumber
5ecf72c3 <= mdb_equality_candidates: (cn) not indexed
5ecf72c3 conn=1067 op=2 SEARCH RESULT tag=101 err=0 nentries=1 text=
5ecf72c3 conn=1067 op=3 ADD dn="cn=everybody,ou=groups,dc=example,dc=org"
5ecf72c3 conn=1067 op=3 RESULT tag=105 err=65 text=invalid structural object class chain (groupOfUniqueNames/posixGroup)
5ecf72c3 conn=1067 op=4 SRCH base="ou=groups,dc=example,dc=org" scope=2 deref=0 filter="(cn=admins,ou=groups,dc=example,dc=org)"
5ecf72c3 <= mdb_equality_candidates: (cn) not indexed
5ecf72c3 conn=1067 op=4 SEARCH RESULT tag=101 err=0 nentries=0 text=
5ecf72c3 conn=1067 op=5 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=device)(cn=lastgid))"
5ecf72c3 conn=1067 op=5 SRCH attr=serialNumber
5ecf72c3 <= mdb_equality_candidates: (cn) not indexed
5ecf72c3 conn=1067 op=5 SEARCH RESULT tag=101 err=0 nentries=1 text=
5ecf72c3 conn=1067 op=6 ADD dn="cn=admins,ou=groups,dc=example,dc=org"
5ecf72c3 conn=1067 op=6 RESULT tag=105 err=65 text=invalid structural object class chain (groupOfUniqueNames/posixGroup)
5ecf72c3 conn=1067 op=7 SRCH base="ou=groups,dc=example,dc=org" scope=2 deref=0 filter="(cn=admins)"
5ecf72c3 conn=1067 op=7 SRCH attr=uniquemember
5ecf72c3 <= mdb_equality_candidates: (cn) not indexed
5ecf72c3 conn=1067 op=7 SEARCH RESULT tag=101 err=0 nentries=0 text=
5ecf72c3 conn=1067 op=8 UNBIND
5ecf72c3 conn=1067 fd=13 closed

**Comment by wheelybird** [comment]
Did you read this?  https://github.com/wheelybird/ldap-user-manager#ldap_uses_nis_schema

**Comment by hryGithub** [comment]
thanks,I ignored this
