### ISSUE TITLE
Navbar links redirecting to HTTP instead of HTTPS

### ISSUE THREAD

**Issue by KPull** [wheelybird/ldap-user-manager#25]
Hi,

I have another problem with regards to HTTPS.

The application is hosted on an HTTPS endpoint: let's say it's accessible on `https://example.com`. It works fine for the most part except for when clicking on the links on the navbar at the top.

Now, I can see that the links themselves have a `href` of, let's say, `/account_manager`, which should be fine, but for some reason when I click on it, it redirects to the HTTP version, `http://example.com/account_manager`.

Is it possible that I'm misconfiguring something?

**Comment by wheelybird** [comment]
I'm not experiencing that behaviour.  As you say, the links don't specify the protocol, so I'm not sure why you're being redirected back to HTTP.  Unless NO_HTTPS is set to true the Apache configuration itself will redirect HTTP to HTTPS.  I'm at a loss to explain it.

**Comment by margru** [comment]
I am experiencing the same issue although I have NO_HTTPS to true as I an using nginx as a proxy (handling HTTPS and redirecting to HTTP upstream). Thus my site is HTTPS, LDAP user manage is HTTP, but all the links should be HTTPS.

**Comment by KPull** [comment]
>  Unless NO_HTTPS is set to true the Apache configuration itself will redirect HTTP to HTTPS.

This is in fact set to `true` in my case as well because the application is behind a reverse proxy that takes care of HTTPS itself.

**Comment by wheelybird** [comment]
Could you share the Nginx configuration?

**Comment by margru** [comment]
@wheelybird Relevant part of my nginx config:
```
upstream lum_servers {
    server 127.0.0.1:17000;
}

server {
    server_name lum.my-domain.com;
    listen 80;
    client_max_body_size 8M;
    proxy_send_timeout 120;
    proxy_read_timeout 300;
    proxy_buffering    off;
    keepalive_timeout  5 5;
    tcp_nodelay        on;

    access_log   /var/log/nginx/lum.access.log combined;
    error_log   /var/log/nginx/lum.error.log warn;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
        proxy_pass_request_headers on;
        proxy_pass http://lum_servers;
    }
}

```

I have also tried to add some cookies and headers related stuff as you can see but it's not working with nor without it.

**Comment by wheelybird** [comment]
In the end this turned out to be down to the Apache DirectorySlash directive which does a redirect if the path is a directory but has no trailing slash.  As you've got this running in NO_HTTPS mode, it's doing a redirect to HTTP, and Nginx doesn't rewrite it.  I've added the trailing slash to the links in the navigation bar which fixes the issue.  Please try again using `latest` or pull `v1.1` again to pick up the change.

**Comment by KPull** [comment]
Works nicely. Good job and thanks!

**Comment by margru** [comment]
@wheelybird I can confirm that this is solved now. Thanks.
