### ISSUE TITLE
Couldn't create LDAP administrators group - Object class violation

### ISSUE THREAD

**Issue by stodge** [wheelybird/ldap-user-manager#27]
I'm sure I'm doing something wrong, but I configured:

`SetEnv LDAP_ADMINS_GROUP "admins"`

But when I run through the setup I get:

```
Updating LDAP...
Couldn't create default group:
Object class violation
⛔ Couldn't create LDAP administrators group:
Object class violation
⛔ The LDAP administration group is empty. What's this?
```

I assume I did something silly?

**Comment by wheelybird** [comment]
This will probably sort you out:  https://github.com/wheelybird/ldap-user-manager#ldap_uses_nis_schema

**Comment by stodge** [comment]
Thanks - I read that but it didn't make sense at the time. More reading required.

**Comment by stodge** [comment]
Thanks - worked beautifully.

**Comment by stodge** [comment]
When your instructions say:

`You can enable RFC2307BIS in osixia/openldap by setting LDAP_RFC2307BIS_SCHEMA to true during the initial setup.`

Do you mean, you have to configure openldap with this setting or ldap-user-manager?

**Comment by wheelybird** [comment]
That's a setting you pass to the osixia/openldap container the first time you run it.

**Comment by stodge** [comment]
Thanks. That's what I thought you meant. I'm using slapd so I'll have to learn how to use the newer schema with it or try this with docker instead. Cheers.
