### ISSUE TITLE
config.inc.php does not take USERNAME_REGEX from environment

### ISSUE THREAD

**Issue by aaachuang** [wheelybird/ldap-user-manager#29]
from the doc, it seems we should be able to overwrite the USERNAME_REGEX from environment variable, but in the code, www/include/config.inc.php does not call getenv.

**Comment by wheelybird** [comment]
Thanks for reporting this.  That's been fixed now.  You can either use `wheelybird/ldap-user-manager:latest` or pull `wheelybird/ldap-user-manager:v1.1` again to get the fix.

**Comment by aaachuang** [comment]
thanks.
