### ISSUE TITLE
Issue after adding admin user

### ISSUE THREAD

**Issue by heronour** [wheelybird/ldap-user-manager#31]
Can you please explain this : 
`
PHP message: PHP Notice:  Undefined index: memberUID in /app/ldap-user-manager/www/includes/ldap_functions.inc.php on line 318PHP message: PHP Warning:  Invalid argument supplied for foreach()`

**Comment by wheelybird** [comment]
Your LDAP schema isn't using memberUID.  See the `LDAP_GROUP_MEMBERSHIP_ATTRIBUTE` in the README.  You probably need to set `LDAP_USES_NIS_SCHEMA` to false.

**Comment by heronour** [comment]
Thank you for the response, but when I change the env var to false I got another issue : 
` PHP Notice:  Undefined index: uniquemember in /app/ldap-user-manager/www/includes/ldap_functions.inc.php on line 361`

**Comment by wheelybird** [comment]
How was your OpenLDAP instance set up?

**Comment by heronour** [comment]
this is my structure: 

![image](https://user-images.githubusercontent.com/1563927/87689546-5a0ae600-c756-11ea-9c40-55deddc2e363.png)

**Comment by wheelybird** [comment]
Sorry, I made a mistake before.  Assuming you haven't enabled the BIS schema in ldap then LDAP_USES_NIS_SCHEMA should be set to true.  This section gives you more information:  https://github.com/wheelybird/ldap-user-manager#ldap_uses_nis_schema

**Comment by heronour** [comment]
Ok I set the variable to true, but when I created an admin account I do not found the management menu on top nav: 

![image](https://user-images.githubusercontent.com/1563927/87694316-08655a00-c75c-11ea-8d48-0b1be443614f.png)

**Comment by wheelybird** [comment]
That's a new one.   Try clearing your cookies or logging in in incognito mode.  If that doesn't work then set `SESSION_DEBUG` to true and post the logs.  This will include passwords, so be sure to redact those.
