### ISSUE TITLE
Add support for stronger password hashes

### ISSUE THREAD

**Issue by Angelin01** [wheelybird/ldap-user-manager#32]
As many should know, the currently stronger hash supported is SSHA, [but even that is getting outdated and is probably left behind sooner rather than later](https://auth0.com/blog/sha-1-collision-attack/).

OpenLDAP, for example, already supports using the OS's crypt library and also SASL. There are also a couple projects which add [PBKDF2 support to OpenLDAP](https://github.com/hamano/openldap-pbkdf2) or even [Bcrypt support](https://github.com/wclarie/openldap-bcrypt).

PhpLdapAdmin already let's users choose "blowfish", "sha256crypt" and "sha512crypt" as password types. Following this trend (and the recently merged #22) it would be lovely if this project could also add similar support. If I can find the time (and with permission from my boss), I could possibly assist in this if necessary.

**Comment by wheelybird** [comment]
Hello.  This should be pretty easy to add to the code, but the reason I didn't do it before is I just didn't have the time to test it.  I'll look into doing it, but I can't say how soon that'll be.

**Comment by Angelin01** [comment]
I have been looking through [PHPLdapAdmin's code](https://github.com/leenooks/phpLDAPadmin/blob/cbdc0dacd62bf66fbf26c4b071e420df0199f47c/lib/functions.php#L2183), and following their example, it seems fairly easy to implement. PHP has all the functions already implemented and even internal fallbacks in case the underlying system does not.
If you do not have time, I can consider trying to add support myself after I am done with a few other things.

**Comment by wheelybird** [comment]
I haven't had a chance to look yet.  If you're able to submit a PR that'd be wonderful.

**Comment by Angelin01** [comment]
I have made progress, which you can accompany [here](https://github.com/Angelin01/ldap-user-manager/tree/better-passwords). From my tests, everything seems to be working.

However, a couple things:
* First one and MOST IMPORTANT, the [change password function](https://github.com/wheelybird/ldap-user-manager/blob/761684b6690bcfcbf622d3d9b5d4c15e0b330e5a/www/includes/ldap_functions.inc.php#L674) is hashing the function but not using it, setting it as cleartext. I have fixed this in my code.
* I let the `PASSWORD_HASH` env variable be invalid in `config.inc.php` and check it on the password hash function, where I can do a warning when I perform a fallback to the strongest function. Maybe there's a better way to do this.
* Checking the phpLDAPadmin code, they do some checks to make sure the functions they use are available. Now, I don't think this is need when using PHP 7+ at all, but I performed similar checks. However, I'm not a PHP programmer, so I don't know the proper way to handle a failure like this, so I simply threw a new exception. What is the best way to do this?

**Comment by wheelybird** [comment]
Thanks a lot for your help with this, and well done on spotting the embarrassing not-even-using-the-hashed-password bug.
With regards to checking for the crypt functions, I'm not really a PHP programmer either.  I think I'd stick with SSHA as the default and if the functions aren't there revert to that but show warnings in the logs, and maybe in the UI (similar to the not-using-TLS warning).

**Comment by Angelin01** [comment]
I have changed the default back to SSHA, but left the other stuff as is, I'm not familiar with the UI stuff or how you'd handle it. I've opened a PR to merge the new implementations. I encourage you to give them a test before you merge, and also to maybe consider looking at how to do those UI warnings you mentioned.
