### ISSUE TITLE
Can't access after adding admin user

### ISSUE THREAD

**Issue by lthieu007** [wheelybird/ldap-user-manager#33]
After i add admin user by : https://x.x.x.x/setup/ 
When i login  https://x.x.x.x/login/
- I show alert:
Warning: preg_grep() expects parameter 2 to be array, null given in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 361
Warning: Cannot modify header information - headers already sent by (output started at /opt/ldap_user_manager/includes/ldap_functions.inc.php:361) in /opt/ldap_user_manager/log_in/index.php on line 27

- I show logs:
[Tue Jul 21 09:31:33.857360 2020] [:error] [pid 26] [client 192.168.76.58:49380] 2020-07-21 09:31:33 - LDAP manager -  -  Failed to start STARTTLS connection to ldap://192.168.32.2: Connect error, referer: https://x.x.x.x/log_in/?

**Comment by wheelybird** [comment]
Hi.  That's not much to go on.  Can you do an ldapsearch and see if the admin user is actually in the admin group?
