### ISSUE TITLE
Issue with SSL/TLS access to OpenLDAP (osixia)

### ISSUE THREAD

**Issue by trahman-hm** [wheelybird/ldap-user-manager#36]
Hello,

I'm attempting to get a test LUM environment configured and married to a test osixia/openldap container.  I'm doing something wrong likely with the SSL/TLS config and I just can't seem to figure it out.  Both containers are running on the same Ubuntu 18.04 LTS install.  I've created a user-defined network in Docker (named ldap-net) to enable direct communication between the containers themselves.

I've genned a ca cert (named ca.crt) and a cert for LDAPS communications used by OpenLDAP, signed by the ca.crt cert.  Those certs (openldap and ca.crt) are in /opt/openldap-certs.  I wanted to have LUM access that same ca.crt file, so I used the LDAP_TLS_CACERT config statement to point to the same dir/file.

osixia/openldap container build script:

docker create \
--name openldap \
--hostname openldap \
--network ldap-net \
-p 636:636 \
-v /opt/openldap-db:/var/lib/ldap \
-v /opt/openldap-config:/etc/ldap/slapd.d \
-v /opt/openldap-certs:/container/service/slapd/assets/certs \
-e LDAP_OPENLDAP_UID=1000 \
-e LDAP_OPENLDAP_GID=1000 \
-e LDAP_ORGANISATION="xxx" \
-e LDAP_DOMAIN="mtd-cust.hmi-inc.com" \
-e LDAP_TLS_CRT_FILENAME=openldap-cert.crt \
-e LDAP_TLS_KEY_FILENAME=openldap-cert.decrypted.key \
-e LDAP_TLS_CA_CRT_FILENAME=ca.crt \
-e LDAP_TLS_VERIFY_CLIENT=never \
-e LDAP_RFC2307BIS_SCHEMA=true \
--restart unless-stopped \
osixia/openldap

LUM build script:

docker create \
--name lum \
--network ldap-net \
-v /opt/openldap-certs:/opt/certs \
-e LDAP_URI=ldaps://openldap \
-e LDAP_BASE_DN=dc=mtd-cust,dc=hmi-inc,dc=com \
-e LDAP_REQUIRE_STARTTLS=TRUE \
-e LDAP_ADMINS_GROUP=admins \
-e LDAP_ADMIN_BIND_DN=cn=admin,dc=mtd-cust,dc=hmi-inc,dc=com \
-e LDAP_ADMIN_BIND_PWD=admin \
-e LDAP_TLS_CACERT=/opt/certs/ca.crt \
-p 6443:443 \
wheelybird/ldap-user-manager

The containers are able to be built/run.  I can get to OpenLDAP via tcp/636 and establish a secure connection using the LDAP Admin client (http://www.ldapadmin.org/) from my Windows laptop (using the admin DN).  My problem is in trying to get LUM to connect to the openldap container using SSL/TLS.  I can get it working with an unencrypted connection (tcp/389) but I get warnings and such - I'd rather see about getting secure communications working if possible.

The Docker logs command against the lum container gives me the following:

Generating RSA private key, 2048 bit long modulus
..+++++
Generating CA key
...............................+++++
e is 65537 (0x010001)
Generating CA certificate
Generating openssl configuration
Generating server key...
Generating RSA private key, 2048 bit long modulus
................................................................................................................+++++
................+++++
e is 65537 (0x010001)
Generating server signing request...
Generating server cert...
Signature ok
subject=CN = example.com
Getting CA Private Key
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
[Thu Jul 30 10:42:18.902015 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.0.33 OpenSSL/1.0.2q configured -- resuming normal operations
[Thu Jul 30 10:42:18.902111 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
example.com:443 192.168.2.1 - - [30/Jul/2020:10:42:30 +0000] "GET /setup/ HTTP/1.1" 200 2395 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.48"
**[Thu Jul 30 10:42:34.573139 2020] [:error] [pid 28] [client 192.168.2.1:35335] 2020-07-30 10:42:34 - LDAP manager -  -  Failed to bind to ldaps://openldap as cn=admin,dc=mtd-cust,dc=hmi-inc,dc=com: Can't contact LDAP server, referer: https://openldap:6443/setup/**
example.com:443 192.168.2.1 - - [30/Jul/2020:10:42:34 +0000] "POST /setup/ HTTP/1.1" 200 323 "https://openldap:6443/setup/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.48"

There is the line above about "Failed to bind..." - I'm assuming that I'm doing something wrong in getting the CA key working so that LUM can successfully connect to OpenLDAP and accept the cert that's advertised.

Is there anything you can see where I've made a mistake so that I can enable successful SSL/TLS communications?

Thanks,

T

**Comment by wheelybird** [comment]
Hi.  You need to set `LDAP_TLS_CACERT` to the contents of the CA cert rather than a file path.   You can use `-e LDAP_TLS_CACERT=$(</path/to/ca.crt)` to get the shell to pass in the file's contents.

**Comment by trahman-hm** [comment]
OK, getting closer.  I'm getting a permission denied during the gen container process with the updated container build script:

docker create \
--name lum \
--network ldap-net \
-v /opt/openldap-certs:/opt/certs \
-e LDAP_URI=ldaps://openldap \
-e LDAP_BASE_DN=dc=mtd-cust,dc=hmi-inc,dc=com \
-e LDAP_REQUIRE_STARTTLS=FALSE \
-e LDAP_ADMINS_GROUP=admins \
-e LDAP_ADMIN_BIND_DN=cn=admin,dc=mtd-cust,dc=hmi-inc,dc=com \
-e LDAP_ADMIN_BIND_PWD=admin \
-e LDAP_TLS_CACERT=$(/opt/openldap-certs/ca.crt) \
-p 6443:443 \
wheelybird/ldap-user-manager

when I gen the container, I get the following:

./create-lum-container: line 1: /opt/openldap-certs/ca.crt: Permission denied

The cert file is owned by my login account on the system.  Is there any way to determine which user/group that LUM is running under so that I can repermission the CA cert file appropriately?  I would rather not give it global read for any/all to get access to the file.

Thanks,

T

**Comment by wheelybird** [comment]
You're missing the `<`.  : `-e LDAP_TLS_CACERT=$(</opt/openldap-certs/ca.crt)`

**Comment by trahman-hm** [comment]
I think we're getting close.  The file is present within the host OS in the following location: /opt/openldap-certs/ca.crt

docker create \
--name lum \
--network ldap-net \
-v /opt/openldap-certs:/opt/certs \
-e LDAP_URI=ldaps://openldap \
-e LDAP_BASE_DN=dc=mtd-cust,dc=hmi-inc,dc=com \
-e LDAP_REQUIRE_STARTTLS=TRUE \
-e LDAP_ADMINS_GROUP=admins \
-e LDAP_ADMIN_BIND_DN=cn=admin,dc=mtd-cust,dc=hmi-inc,dc=com \
-e LDAP_ADMIN_BIND_PWD=admin \
-e LDAP_TLS_CACERT=$(</opt/openldap-certs/ca.crt) \
-p 6443:443 \
wheelybird/ldap-user-manager

When I attempt to create the container, I get the following:

invalid reference format: repository name must be lowercase

Thanks,

T

**Comment by trahman-hm** [comment]
OK, think I've got it.  Found a reference to the error here:

https://stackoverflow.com/questions/48522615/docker-error-invalid-reference-format-repository-name-must-be-lowercase

There was some comments about the error related to the linked items needing to be quoted.  So I tried this:

docker create \
--name lum \
--network ldap-net \
-e LDAP_URI=ldaps://openldap \
-e LDAP_BASE_DN=dc=mtd-cust,dc=hmi-inc,dc=com \
-e LDAP_REQUIRE_STARTTLS=FALSE \
-e LDAP_ADMINS_GROUP=admins \
-e LDAP_ADMIN_BIND_DN=cn=admin,dc=mtd-cust,dc=hmi-inc,dc=com \
-e LDAP_ADMIN_BIND_PWD=admin \
-e LDAP_TLS_CACERT="$(</opt/openldap-certs/ca.crt)" \
-p 6443:443 \
wheelybird/ldap-user-manager

and it now seems to work.

Thanks,

T

**Comment by stodge** [comment]
Would you mind posting your docker commands for openldap and lum to help others (me!!)? I'm struggling with this too. Thanks

**Comment by wheelybird** [comment]
Could you post your Docker run command and any errors you're getting?

**Comment by stodge** [comment]
I'm still learning about ssl/starttls so what I have so far is probably very naive:

```
sudo docker run \
             --detach \
             --name=lum \
             --restart unless-stopped \
             -p 80:80 \
             -p 443:443 \
             -e SERVER_HOSTNAME=auth.xxxx.xxx \
             -e LDAP_URI=ldap://172.17.0.2 \
             -e LDAP_BASE_DN=dc=wheelybird,dc=com \
             -e LDAP_ADMINS_GROUP=admins \
             -e LDAP_ADMIN_BIND_DN="cn=admin,dc=wheelybird,dc=com" \
             -e LDAP_ADMIN_BIND_PWD=PASSWORD \
             -e NO_HTTPS=false \
             wheelybird/ldap-user-manager:latest
```

When I try to connect using ldap-user-manager (docker) I'm getting:

TLS: can't accept: No certificate was found.

Thanks

**Comment by wheelybird** [comment]
The "TLS: can't accept" message is your LDAP server not allowing connections for clients that don't have a client certificate.  You'll need to update your LDAP server config to fix this.  If you're using `osixia/docker-openldap` then you'll need to change LDAP_TLS_VERIFY_CLIENT from the default.  See https://github.com/osixia/docker-openldap#defaultstartupyaml (search for LDAP_TLS_VERIFY_CLIENT).  You should probably set it to `try`.

**Comment by stodge** [comment]
Thanks. I still get the same problem:

OpenLDAP:

```
5fe0de31 conn=1000 op=0 RESULT oid= err=0 text=
TLS: can't accept: No certificate was found..
5fe0de31 conn=1000 fd=12 closed (TLS negotiation failure)
```

LUM:

```
Failed to start STARTTLS connection to ldap://172.17.0.2: Connect error, referer: http://auth.xxxx.xxx/log_in/
```

**Comment by stodge** [comment]
ldap-user-manager can now connect to OpenLDAP, but I'm having other problems, which aren't relevant to this topic. Thanks
