### ISSUE TITLE
Add external members to group

### ISSUE THREAD

**Issue by bpnx** [wheelybird/ldap-user-manager#37]
Hello, I'd like to permit a admin user to create users on subtree ou=people,... , but I'd like to permit that admin
to add people from ou=externalpeople,.... on the groups he creates (but I don't want to permit him to create users
on ou=externalpeople,...). Does ldap-user-manager support this kind of configuration ?
Thanks
Marco

**Comment by wheelybird** [comment]
Hi.  Sorry but no, it doesn't.  This project focuses on quick-and-easy user account and group set-up and management, and I think what you're after is somewhat niche I'm afraid.

**Comment by bpnx** [comment]
Yes, I know, it's not a common need :-(
Thank you
Marco
