### ISSUE TITLE
Example docker-compose.yml

### ISSUE THREAD

**Issue by cxkoda** [wheelybird/ldap-user-manager#38]
Hey hey, nice project.
It would be very useful to have a basic `docker-compose.yml` file as an example and a starting point for more complex setups.
Since you mention `osixia/openldap` explicitly in the readme, could please provide such a setup with this backend and your frontend?

Best, cx

**Comment by cxkoda** [comment]
Never mind, I overlooked the example at the bottom of the `README.md`. Sorry for the noise.

**Comment by flavienbwk** [comment]
Hmm, why did this issue have been closed ? Might be useful to have a docker-compose example !

**Comment by mcruzdev** [comment]
It is very useful
