### ISSUE TITLE
Using LUM for a Samba4 ADDC management?

### ISSUE THREAD

**Issue by Koratsuki** [wheelybird/ldap-user-manager#39]
**First of all, great work!**
==
Note: ADDC stands for "Active Directory Domain Controller"

Guys, how can I use LUM for a Samba4 ADDC management? Have you tested it? Need some ideas, cause I want to eliminate RSAT, to manage users and groups on a fresh ADDC install.

I have a LUM running instance with Nginx and works like a charm[connects to the ADDC], but... On the setup step, about "The group defining LDAP account administrators" gives me an error, telling that "The LDAP administration group is empty.", but the group have admin users inside[memberOf]. If I'm skipping something I will really appreciate if you point me in the right direction.

My current settings[config.inc.php]:
$LDAP['uri'] = 'addc.inutil.cu';
$LDAP['base_dn'] = 'dc=inutil,dc=cu';
$LDAP['admins_group'] = 'cn=LocalAdmins';
$LDAP['admin_bind_dn'] = 'INUTIL\Administrator';
$LDAP['admin_bind_pwd'] = 'Adm1n*P4s$w0rd';

**Comment by wheelybird** [comment]
Hi.  Unfortunately this project doesn't support ADDC - it's specifically an LDAP account management GUI, and a relatively basic one at that (only supporting user & group creation).   Samba4 ADDC uses a non-LDAP backend and a much more complicated schema, and there are no plans to support that.

**Comment by Koratsuki** [comment]
Thanks anyway, keep up the good work. Regards!
