### ISSUE TITLE
Send a mail tu the newly created user

### ISSUE THREAD

**Issue by xgaia** [wheelybird/ldap-user-manager#41]
When an admin add a new user, send a mail to the new user to let him know about his account. 

In the mail, add a link to change the password.

**Comment by wheelybird** [comment]
That sounds like a reasonable idea.  I'll look into implementing it, but I won't be able to start for a couple of weeks at least.

**Comment by wheelybird** [comment]
This has been added in v1.3.  An external SMTP server is needed to be able to send emails.

**Comment by xgaia** [comment]
thank you very much, I will try that !
