### ISSUE TITLE
Fails to open ldap after creation

### ISSUE THREAD

**Issue by theshades** [wheelybird/ldap-user-manager#43]
My Compose File:
`version: '2'
services:
  ldapwebui:
    image: wheelybird/ldap-user-manager:latest
    ports:
      - "1380:80/tcp"
      - "13443:443/tcp"
    volumes:
      -  ldapwebvar:/var
    environment:
      - SERVER_HOSTNAME=myapp.penguinzmedia.group
      - LDAP_URI=ldap://localhost:389
      - LDAP_ADMIN_BIND_PWD=redacted
      - MAIL_DOMAIN=penguinzmedia.group
      - LDAP_DOMAIN=penguinzmedia.group
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=penguinzmedia,dc=group
      - LDAP_ADMINS_GROUP=cn=admins,ou=groups,dc=penguinzmedia,dc=group
      - LDAP_BASE_DN=dc=penguinzmedia,dc=group
      - LDAP_REQUIRE_STARTTLS=false
volumes:
  ldapwebvar:
    driver: local
`
Docker Version: Docker version 19.03.13, build 4484c46d9d
Docker Host Version:
`Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
`
docker-compose version 1.17.1, build unknown

Error thrown by webpage:
`
Warning: preg_grep() expects parameter 2 to be array, null given in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 452

Warning: Cannot modify header information - headers already sent by (output started at /opt/ldap_user_manager/includes/ldap_functions.inc.php:452) in /opt/ldap_user_manager/log_in/index.php on line 27`

**Comment by wheelybird** [comment]
Hi.  Check the logs; they'll give you more information on errors.  You can enable verbose logs with `LDAP_DEBUG=true`.  It's likely this is a schema issue.  Have you read https://github.com/wheelybird/ldap-user-manager#a-note-on-your-ldap-schema ?
