### ISSUE TITLE
Pass-Through authentication with SASL

### ISSUE THREAD

**Issue by insatomcat** [wheelybird/ldap-user-manager#44]
Hello,

I would love to use ldap-user-manager but I need to setup pass-through authentication to another LDAP server. What I usually do is set the userPassword attribute of a user to "{SASL}username" to that openldap will use SASL for this user, and thus delegate the authentication to another server.
Is there any way I can do that with ldap-user-manager ?

Thanks.

**Comment by wheelybird** [comment]
Hi.
I can't say for sure if this'll work, but if you set `PASSWORD_HASH` to `CLEAR` and `ACCEPT_WEAK_PASSWORDS` to `TRUE` then you should be able to set the password to `{SASL}user@domain` when setting up a user.  Of course the self-service password changing stuff isn't going to work even if this does.

**Comment by insatomcat** [comment]
Thanks.
Even with the PASSWORD_HASH=CLEAR option, I can still see the passwords stored with SSHA. Something I'm doing wrong?

**Comment by wheelybird** [comment]
No, you've spotted a stupid bug.  I'll push a fix ASAP.

**Comment by wheelybird** [comment]
If you run `docker pull wheelybird/ldap-user-manager:latest` and try again, hopefully that'll work.

**Comment by insatomcat** [comment]
Thanks it's fine now. I still have to play with sasl and the osixia/openldap image.

In the meantine, may I suggest 2 improvements that would help with my use case:
- Even if PASSWORD_HASH could stay as the default hashing algorithm, it'd be great to be able to choose the algorithm for each user (with a dropdown list like phpldapadmin has). That way I could choose for each user whether I want sasl (in which case CLEAR is fine) or if want to set a real passwd (in which case CLEAR is a really bad idea).
- for typing a SASL userPassword, the "confirmation" and the "secret" typing is a little problem. A feature to either select a "secret" typing (with a necessary confirm textbox), or a "non secret" (show password) typing (with no confirmation textbox) would be great.

Thanks

**Comment by wheelybird** [comment]
Really the purpose of this project is simple user and group management and these features would be outside of that scope.  Saying that, I'd be delighted to accept pull requests if this is something you feel you'd be able to implement.
