### ISSUE TITLE
good starttls connection not detected

### ISSUE THREAD

**Issue by PhiVag** [wheelybird/ldap-user-manager#46]
Hello,
First I really like the look of this app.
I believe a good starttls connection is not detected and at setup the warning `Unable to connect to ldap://mydomain.com via STARTTLS. What's this?` is not appropriate.
From what I see in the run_checks.php the two values `$LDAP['starttls']` and `$ENCRYPTED` are never set. Not sure if that means that starttls is not used afterwards.
I have added ldap debug options and I can see that the starttls connection is successful. 
Best

**Comment by wheelybird** [comment]
Hi.  Thanks for that.  This should be fixed in the next release (hopefully before Christmas if I can find the time).

**Comment by wheelybird** [comment]
This has been fixed in v1.3.  Thanks for reporting it.
