### ISSUE TITLE
Signup form

### ISSUE THREAD

**Issue by xgaia** [wheelybird/ldap-user-manager#50]
A form to create a, account without asking an admin will be nice

**Comment by wheelybird** [comment]
Hi.  Thanks for the suggestion.  I don't really understand the use case 
for this, though.  Most of the time people use LDAP as authentication 
for private systems such as server access, access to internal web 
utilities like Jenkins or company user accounts for email etc., in which 
case you want some kind of approval system in place for creating those 
accounts.
How do you intend to use this self-service account creation?

**Comment by xgaia** [comment]
Hi @wheelybird, I use LDAP authentication for several public services (Nextcloud, Gitea, RocketChat ...)

Currently, new users send me an email, and I create an account for them using your tool (thanks by the way :+1 : )

I would like to have a form for new users to register themselves. An approval system would be a good idea to avoid spam.

**Comment by wheelybird** [comment]
This is available in release v1.5 (Docker image wheelybird/ldap-user-manager:v1.5)
