### ISSUE TITLE
Change password at the first login

### ISSUE THREAD

**Issue by jtheo** [wheelybird/ldap-user-manager#52]
Hi, 
I hope it's not a duplicate or already discussed; I couldn't find anything in the other issues.

Could it be possible to update the password and force the user to change it again at the first login?

This could also be linked to the [Forgot password feature/email new credentials on account change #48](https://github.com/wheelybird/ldap-user-manager/issues/48)

**Comment by wheelybird** [comment]
Hi.  This isn't really possible at the moment.  It would require the password policy module to be enabled and that's something that the LDAP administrator would need to do - this utility has no access to `cn=config` to start, and setting up password policies is non-trivial.
I haven't checked this, but it might be possible to simply create accounts with the pwdPolicy object class without password policies being enabled but all this would achieve is to add an attribute that this utility could check for when people log in to see if the password needs to be reset, but the user would still be able to log into anything else that's using LDAP authentication, so I don't really see the benefit (and of course there would be the issue of backwards-compatibility for all accounts that were created before that object class was used).

**Comment by jtheo** [comment]
I see, thank you very much for your answer.
