### ISSUE TITLE
Using LUM with Apache ReverseProxy

### ISSUE THREAD

**Issue by jonathanwerle** [wheelybird/ldap-user-manager#53]
I have multiple services running on my server, one is Apache. Therefore i can't/won't run LUM with ports 80/443 exposed. I tried to setup a reverse proxy with Apache (which i am using to access other Docker containers on my server) and i am able to open the login page using _https://user.example.com_. But after login, LUM redirects to https\://user.example.com:5477/index.php?logged_in (**please notice the port after the domain** -> 5477 is exposed 443 port of docker container). 

This is my apache config:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName user.example.com
        SSLProxyEngine On

        ProxyPass / http://localhost:5476/ nocanon
        ProxyPassReverse / http://localhost:5476/

        SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

Does someone know how to block redirects to the port in Apache config? Maybe this isn't even possible.
Or otherwise can someone help me use my existing SSL certificate for LUM?

**Comment by wheelybird** [comment]
Hi.  Could you post your Docker run settings? ProxyPassReverse should handle removing the port from the Location header normally, though you say it's redirecting to port 5477 and the ProxyPass settings are for port 5476.

**Comment by jonathanwerle** [comment]
Hi! Thanks for your response! I start LUM with the following command:
```
docker run \
        --detach \
        -h example.com \
        --name=lum \
        -p 5476:80 \
        -p 5477:443 \
        -e "SERVER_HOSTNAME=user.example.com" \
        -e "LDAP_URI=ldap://172.17.0.1" \
        -e "LDAP_BASE_DN=dc=example,dc=com" \
        -e "LDAP_REQUIRE_STARTTLS=FALSE" \
        -e "LDAP_ADMINS_GROUP=admins" \
        -e "LDAP_ADMIN_BIND_DN=cn=admin,dc=example,dc=com" \
        -e "LDAP_ADMIN_BIND_PWD=CENSORED" \
        -v "/home/myuser/test:/opt/ssl" \
        wheelybird/ldap-user-manager:v1.2
```

I understand how my last comment caused confusion about the ports, but i am sure about the ports. I am using https on port 80 to access Apache, which redirects me internally (ReverseProxy) to http port 5476 of my docker container (same server).

In this line `-v "/home/myuser/test:/opt/ssl" \` i tried to copy my letsencrypt certificates to the container.

**Comment by wheelybird** [comment]
I had trouble replicating this, but could you try adding `ProxyPreserveHost On` to your Apache config to see if that helps?

**Comment by wheelybird** [comment]
With regards to the SSL certificates, it's specifically looking for `server.key` and `server.crt`, so you might need to copy your LetsEncrypt files to those, or maybe symlink them.  There's a bug with importing `chain.pem` though, so perhaps that's causing your issue with using your own certs?

**Comment by jonathanwerle** [comment]
First of all: Thank you for this amazing software and your efforts to solve this problem @wheelybird!

I wanted a solution to setup Apache reverse proxy with LUM as a docker container. With your help and some own research i created the following apache config, which works great for me (5477 is my exposed port for 443):

```
<VirtualHost *:443>
    ServerAdmin webmaster@example.domain
    ServerName user.example.domain

    LogLevel info
    ErrorLog /var/log/apache2/lum-error.log
    TransferLog /var/log/apache2/lum-access.log

    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off

    ProxyPreserveHost On
    ProxyPass / https://localhost:5477/
    ProxyPassReverse / https://localhost:5477/

    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/example.domain/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.domain/privkey.pem
</VirtualHost>
```

**Comment by wheelybird** [comment]
Great stuff.  Glad you managed to get it working!
