### ISSUE TITLE
Undefined variable: LDAP_VERBOSE_CONNECTION_LOGS

### ISSUE THREAD

**Issue by cyberb** [wheelybird/ldap-user-manager#54]
I get this error:

Dec 12 10:26:45 23563d0b6dcc [1345]: PHP Notice:  Undefined variable: LDAP_VERBOSE_CONNECTION_LOGS in /snap/users/x1/www/includes/ldap_functions.inc.php on line 21

https://github.com/wheelybird/ldap-user-manager/blob/8dacee9c4e8c58d8e7c3ecf0248b09e394f7ef85/www/includes/ldap_functions.inc.php#L21

**Comment by wheelybird** [comment]
Cheers for reporting this.  It'll be fixed in the next update.

**Comment by wheelybird** [comment]
This should be fixed in release v1.5 (Docker image wheelybird/ldap-user-manager:v1.5)
