### ISSUE TITLE
SMTP servers with no authentication do not work

### ISSUE THREAD

**Issue by glward** [wheelybird/ldap-user-manager#57]
Setting just `SMTP_HOSTNAME` without setting `SMTP_USERNAME` or `SMTP_PASSWORD` still results an attempt to use authentication with an empty string for the user and password, which fails. 

I was able to work around this by changing the assignment in `config.inc.php` to:

```php
 $SMTP['user'] = (getenv('SMTP_USERNAME') ? getenv('SMTP_USERNAME') : NULL);
 $SMTP['pass'] = (getenv('SMTP_PASSWORD') ? getenv('SMTP_PASSWORD') : NULL);
```

**Comment by wheelybird** [comment]
Cheers!  I've added that and updated the Docker images with the fix.
