### ISSUE TITLE
Allow special chars (utf8) in group/user names

### ISSUE THREAD

**Issue by nkoester** [wheelybird/ldap-user-manager#61]
I am unable to create groups such as 'naturtrüb'. Using the phpLDAPadmin interface I am able to create them. However, when I try to add/remove user to this group with the ldap-user-manager I get an error saying 'The group name is invalid.' Would support for utf8 be possible?

**Comment by wheelybird** [comment]
In the latest release (v1.6) you can set `ENFORCE_SAFE_SYSTEM_NAMES` to `FALSE`.  This should allow you to use accented characters.
