### ISSUE TITLE
SERVER_HOSTNAME set, but site still goes to private IP

### ISSUE THREAD

**Issue by kp3nguinz** [wheelybird/ldap-user-manager#63]
I have this app on a docker cluster behind a reverse proxy in GCP. However, when I try to access setup and certain aspects, it pushes me to the private ip.  Shouldn't SERVER_HOSTNAME be what the redirects are to? If not, can they can be please?

**Comment by wheelybird** [comment]
Redirects go to HTTP_HOST which Apache sets from the Host: header the client sends.  If you're behind a reverse proxy then the proxy is the client, so it seems like it's not passing the hostname onto Apache.  Which reverse proxy are you using?  Can you post the configuration?

**Comment by kp3nguinz** [comment]
hmm, this helps. Let me dig a bit more.

**Comment by kp3nguinz** [comment]
I had turned the ProxyPreserveHost flag not enabled ( I run a generic build with things commented out unless I need it).
Posting the correct config for anyone in the future running Apache Reverse Proxy:
` <Location / >
ProxyPass  https://10.172.0.7:3443/
ProxyPassReverse   https://10.172.0.7:3443/
ProxyPreserveHost On
#RequestHeader set "X-Forwarded-Proto" "https"
#Order deny,allow
#Deny from all
#ProxyHTMLEnable On
#ProxyHTMLURLMap  /  /authui/
#ProxyHTMLExtended On
RequestHeader    unset  Accept-Encoding
Allow from all
</Location>
`
