### ISSUE TITLE
Using lum with existing schema

### ISSUE THREAD

**Issue by gerold-krommer** [wheelybird/ldap-user-manager#65]
Hi,
my ldap know-how is pretty basic so pls bear with me.
I have a completely set up (by a 3rd party) software demo and development environment (conatinerized) with a populated osixia/openldap container. I run this in a VMware Workstation 16 under Ubuntu 20.04.

As this is preset I have little to no influence on how the ldap environment was created. SSL I do not need. I can work with the demo software so the ldap works alright. I want to 'spice up' the enviroment with easier user/group management.

When running the container with

`sudo docker run --name olgui -e "SERVER_HOSTNAME=localhost" -e "LDAP_URI=ldap://172.17.0.3" -e "LDAP_BASE_DN=dc=ecm,dc=ibm,dc=com" -e "LDAP_ADMINS_GROUP=admins" -e "LDAP_ADMIN_BIND_DN=cn=P8Admin,dc=ecm,dc=ibm,dc=com" -e "LDAP_ADMIN_BIND_PWD=somepass" -e "LDAP_IGNORE_CERT_ERRORS=true" -e "NO_HTTPS=TRUE" -e "LDAP_REQUIRE_STARTTLS=FALSE" -e "LDAP_RFC2307BIS_SCHEMA=TRUE" wheelybird/ldap-user-manager:latest`

The console shows

`ocalhost:80 172.17.0.1 - - [29/Jan/2021:23:23:22 +0000] "GET / HTTP/1.1" 200 668 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
localhost:80 172.17.0.1 - - [29/Jan/2021:23:23:29 +0000] "GET /log_in/ HTTP/1.1" 200 917 "http://172.17.0.6/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[Fri Jan 29 23:23:38.809974 2021] [:error] [pid 23] [client 172.17.0.1:45410]  Failed to bind to ldap://172.17.0.3 as cn=P8Admin,dc=ecm,dc=ibm,dc=com: Can't contact LDAP server, referer: http://172.17.0.6/log_in/
localhost:80 172.17.0.1 - - [29/Jan/2021:23:23:38 +0000] "POST /log_in/ HTTP/1.1" 200 288 "http://172.17.0.6/log_in/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[Sat Jan 30 07:51:27.161477 2021] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully`

Replacing localhost with the ip lum is running on (172.17.0.6) or removing the LDAP_RFC2307BIS_SCHEMA=TRUE  makes no difference. The openldap runs on 172.17.0.3

I logged 'into' the lum container and issued a
`curl ldap://172.17.0.3`

and back comes
`root@bb087bf39196:/var/www/html# curl ldap://172.17.0.3
DN: 
	objectClass: top
	objectClass: OpenLDAProotDSE`

So connectivity works...
I'm pretty sure the P8Admin password is correct.

I#m sure the fault is on m side. I'm seeking a way to debug this better.

Thanks,
/Gerold

**Comment by wheelybird** [comment]
Hi.  From the logs I'm not sure what the issue is.  You can get more verbose logs if you set `LDAP_VERBOSE_CONNECTION_LOGS` and `LDAP_DEBUG` to `TRUE`.  That might give us some more information, though if you plan to post the logs you'll want to redact any passwords from them.
