### ISSUE TITLE
Ability not to run with HTTPS

### ISSUE THREAD

**Issue by Kanshiroron** [wheelybird/ldap-user-manager#7]
Hello,
First of all, thanks for the project!

I would like to know if it would be possible to add an option where Apache2 is started without TLS (and obviously not redirect/cert generation). I asking that because we are using it behind an ingress (Kubernetes deployment), which is in charge of offloading the TLS.
I managed to make it work now with TLS re-encryption but would be a little cleaner without.

Thanks for your help!

**Comment by wheelybird** [comment]
This would be a non-trivial change, and of course TLS is quite important when you're sending all those important passwords across networks.   Even with a load-balancer offloading TLS it's a good idea to have TLS between the balancer and Apache so that nothing on the same network as Apache can sniff the traffic.
Was the issue with the Kubernetes ingress due to the use of self-signed certificates?

**Comment by Kanshiroron** [comment]
There isn't much issues using it with Kubernetes per say, it is more in the way certificate renewal is handled.
What's usually done when using Kubernetes, is that certificates are managed by Certificate manager, which is a nice tool to manage certificate renewal (from private CA, Let's Encrypt, etc...), and most (if not all) Kubernetes ingresses are able to update them without restarting.
But since here the certificate is deployed inside the container we lost this ability.
I know a workaround would be to use a long expiry certificate but that's not ideal either.

**Comment by wheelybird** [comment]
The self-signed certificate that's generated is good for 7300 days and a new one is generated each time the container starts (unless you bind-mount a local directory to `/opt/ssl` in the container).

**Comment by gabri94** [comment]
I agree with @Kanshiroron, i would like the ability to disable completely SSL and rely only on my reverse proxy

**Comment by wheelybird** [comment]
In the latest version you can pass `-e NO_HTTPS=TRUE`  to docker and this will run Apache in HTTP only mode.  Don't forget to publish port 80.  The 'latest' image on Docker Hub has been updated with these changes.
I still don't recommend running without encryption as obviously someone/something on the network between your reverse-proxy and this service can sniff traffic and see all the beautiful passwords.
