### ISSUE TITLE
How to enable NIS schema on openldap (to be compatible with ldap-user-manager)

### ISSUE THREAD

**Issue by couling** [wheelybird/ldap-user-manager#70]
I realise this is a bit of an openldap question, but since I'm doing it solely to setup ldap-user-manager and the README says _"It's designed to work with OpenLDAP"_, I'll ask it here.

I'm getting an error very similar to https://github.com/wheelybird/ldap-user-manager/issues/24 Openldap reports 
```
conn=1007 op=14 RESULT tag=105 err=65 text=invalid structural object class chain (groupOfUniqueNames/posixGroup)
```
I have of course read [this](https://github.com/wheelybird/ldap-user-manager#using-the-rfc2307bis-schema):

>With OpenLDAP this schema isn't normally available by default; you need to configure your server to use the RFC2307BIS schema when setting up your directory.

However I don't see any instructions here on how to enable it.  From a fresh openldap install (alpine `apk add ...`). I've added the schemas to slapd.conf:

```
include     /etc/openldap/schema/core.schema
include     /etc/openldap/schema/cosine.schema
include     /etc/openldap/schema/nis.schema
```
I've then converted to cn=config and granted access to my rootdn to `manage` cn=config.  I've confirmed access and the presence of the schemas by logging in with python-ldap I can confirm that these all exist and are accessible by the rootdn:
```
cn={0}core,cn=schema,cn=config
cn={1}cosine,cn=schema,cn=config
cn={2}nis,cn=schema,cn=config
```
For testing atleast I've logged ldap-user-manager in as the rootdn (same as python-ldap).  But I still see the warning and error as per the other issue.

Is there something obvious I'm missing setting this up?

**Comment by wheelybird** [comment]
I'm not familiar with the Alpine OpenLDAP package.  Looking at the package contents online it looks like they don't include the schema.   You'll need to find `rfc2307bis.schema` somewhere on the internet and use that in place of the nis.schema (maybe this one?  https://github.com/jtyr/rfc2307bis)
If you're starting a new directory then that should be simple enough.  If not then you'll have to remove the nis schema and add in the rfc2307bis schema.  This might help:  https://serverfault.com/questions/631652/openldap-how-to-remove-the-nis-schema-from-the-current-configuration

**Comment by couling** [comment]
I have a few distros to hand, and can always peek inside another via docker run... could you name a distro and schema file name (where to find it on the system after install).  [rfc2307bis.schema](https://github.com/jtyr/rfc2307bis) looks a lot like `/etc/openldap/schema/nis.schema` right down to the attribute names and OIDs.  If the OIDs match it should be the same schema or else someone did something very naughty.

**Comment by wheelybird** [comment]
I use osixia/docker-openldap.  Here's their rfc2307bis.schema: https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/assets/config/bootstrap/schema/rfc2307bis.ldif
There's not much difference between that and the NIS schema.  With the BIS schema, posixAccount is AUXILIARY - that's what I use to try and autodetect rfc2307bis.

**Comment by couling** [comment]
Oh good god that's confusing as hell!

Here's my problem:  https://unofficialaciguide.com/2019/07/31/ldap-schemas-for-aci-administrators-rfc2307-vs-rfc2307bis/

RFC2307**bis** isn't an official standard, it never left draft.  It differs from RFC2307, at the very least it has additional object classes.  It looks like everyone went ahead and used it anyway.  OpenLdap ships with nis.scheama which covers RFC2307.  Normally there's no overlap between OIDs and RFC but this is a draft modifying a published RFC.  It's a pretty major trip hazard!

Would you mind updating your README so that it highlights that RFC2307 is not RFC2307biz and openldap's `nis.schema` isn't enough.  You might also like to provide a link (eg: the one above).

**Comment by wheelybird** [comment]
The README in the latest release (v1.6) has been modified to make that link a bit more prominent.  However I don't think the README for the user manager is the best place to go into the differences between the RFC2307s.
