### ISSUE TITLE
[feature request] prevent deletion of admins group

### ISSUE THREAD

**Issue by mozzbozz** [wheelybird/ldap-user-manager#71]
It's currently possible to delete the `admins` group (or whichever name is defined in the `LDAP_ADMINS_GROUP` environment variable). Obviously that's not a great idea and results in the user not being able to log in anymore, throwing some errors.

I think it would make sense to prevent the user from being able to delete that group or (if I missed a case where it actually makes sense) display a warning that he might break the system...

**Comment by wheelybird** [comment]
That makes sense. :D

**Comment by wheelybird** [comment]
That's been added to the latest release (v1.6).
