### ISSUE TITLE
Question regarding warning "Unable to connect to ldaps://openldap:636 via STARTTLS." when ldaps is used

### ISSUE THREAD

**Issue by mozzbozz** [wheelybird/ldap-user-manager#72]
Hi, after some hours of playing around with this great tool (thank you!) I have a question: Is StartTLS even possible when using ldaps or are those to exclusive to each other? If so: Shouldn't the warning on the setup screen not be displayed when using `ldaps`? (the yellow warning at the bottom of the page isn't displayed after all when ldaps is enabled but StartTLS not).

So if I enable ldaps *and* `LDAP_TLS_VERIFY_CLIENT=demand` in the `osixia/openldap` container at the same time while trying to access the openldap server with ldap-user-manager via ldaps, it simply can't work, right?

Or am I completely misunderstanding something about StartTLS vs. ldaps? Thanks!

EDIT: Sorry, somehow managed to send this issue in with the keyboard enter key before finishing the description. Appended it now.

**Comment by wheelybird** [comment]
TLS and LDAPS are indeed different and any TLS settings won't affect the LDAPS connection.   So yes, we shouldn't display TLS warnings when using LDAPS.
LDAPS connections are entirely encrypted (you connect to a secure port) whereas StartTLS starts as a unencrypted connection and then uses TLS to encrypt traffic over that connection.
I'll make the changes - they'll be in the next release.

**Comment by wheelybird** [comment]
That's been added to the latest release (v1.6).
