### ISSUE TITLE
supress warning

### ISSUE THREAD

**Issue by cyberb** [wheelybird/ldap-user-manager#73]
Is there any way to supress this warning?
I am using localhost only connection so it is secure.
Also this message is only visible on users and groups pages but not on password change page.

```
WARNING: Insecure LDAP connection to ldap://localhost
```

**Comment by wheelybird** [comment]
That should be gone in the latest update to the branch.

**Comment by cyberb** [comment]
Strange, I see your commit on use_other_attributes, but it still shows on my selenium test screens on the latest build.

**Comment by wheelybird** [comment]
That's been added to the latest release (v1.6).

**Comment by cyberb** [comment]
Still see it on 1.6
http://ci.syncloud.org:8081/files/users/181-amd64/screenshot/add-user-before-open-desktop.png
