### ISSUE TITLE
Cannot add admin user

### ISSUE THREAD

**Issue by kp3nguinz** [wheelybird/ldap-user-manager#79]
**Check the debugging logs**

`** ld 0x56127db2b050 Connections:
* host: openldap  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Sun Mar 14 09:50:04 2021

** ld 0x56127db2b050 Outstanding Requests:
 * msgid 26,  origid 26, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x56127db2b050 request count 1 (abandoned 0)
** ld 0x56127db2b050 Response Queue:
 * msgid 26,  type 100
  ld 0x56127db2b050 response count 1
ldap_chkResponseList ld 0x56127db2b050 msgid 26 all 1
ldap_chkResponseList returns ld 0x56127db2b050 NULL
ldap_int_select
read1msg: ld 0x56127db2b050 msgid 26 all 1
read1msg: ld 0x56127db2b050 msgid 26 message type search-result
read1msg: ld 0x56127db2b050 0 new referrals
read1msg:  mark request completed, ld 0x56127db2b050 msgid 26
request done: ld 0x56127db2b050 msgid 26
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 26, msgid 26)
adding response ld 0x56127db2b050 msgid 26 type 101:
ldap_parse_result
ldap_first_attribute
ldap_get_values_len
ldap_next_attribute
ldap_get_dn
[Sun Mar 14 09:50:04.122455 2021] [:error] [pid 26] [client 10.128.0.7:46502]  LDAP returned 0 members of admins when using this search: (cn=admins) and this filter: uniquemember, referer: https://exampleserver/setup/run_checks.php
ldap_msgfree
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
exampleserver.group:443 10.128.0.7 - - [14/Mar/2021:09:50:04 +0000] "POST /setup/setup_ldap.php HTTP/1.1" 200 3300 "https://exampleserver/setup/run_checks.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"`
**Version**
Running the version: https://github.com/Penguinz-Media-Group/ldap-user-manager

**Describe the bug**
Getting to a point where all of the LDAP stuff is good to go, but it wont let me get past adding an admin account during setup. When I click the create new account button, nothing happens, and no log entries are added even in debug.  When I manually do it with an external tool everything works as expected. 
![image](https://user-images.githubusercontent.com/18054435/111064330-48eeb200-8468-11eb-8ac1-47551085a196.png)

A bit more:
Running the latest osxia ldap docker server

**Comment by wheelybird** [comment]
Hi. Do you mean when you click the button it reloads the same page or just does nothing at all?
