### ISSUE TITLE
Users list is not displayed

### ISSUE THREAD

**Issue by Kanshiroron** [wheelybird/ldap-user-manager#8]
Hello,

I'm facing an issue with the WebUI where no user is displayed but the ldap query returns some:

According to the OpenLDAP logs, here is the query that is performed by the app, and we see that the LDAP DB is returning 2 entries:
```
5dc57eea conn=92245 op=2 SRCH base="ou=users,dc=example,dc=com" scope=2 deref=0 filter="(&(cn=*))"
5dc57eea conn=92245 op=2 SRCH attr=uid givenname sn mail
5dc57eea conn=92245 op=2 SEARCH RESULT tag=101 err=0 nentries=2 text=
```
And indeed, running the query with `ldapsearch`, I do see the fields being returned:
```
ldapsearch -b "ou=users,dc=example,dc=com" "(&(cn=*))" uid givenname sn mail 
# extended LDIF
#
# LDAPv3
# base <ou=users,dc=example,dc=com> with scope subtree
# filter: (&(cn=*))
# requesting: uid givenname sn mail 
#

# user1, users, example.com
dn: cn=user1,ou=users,dc=example,dc=com
givenName: User 1
sn: User 1
uid: user1
mail: user1@example.com

# user2, users, example.com
dn: cn=user2,ou=users,dc=example,dc=com
givenName: User2
sn: User2
uid: user2
mail: user2@example.com

# search result
search: 3
result: 0 Success

# numResponses: 3
# numEntries: 2
```

Thank you for your help!

**Comment by wheelybird** [comment]
Hi.  I didn't test the code using the CN as the account identifier (LDAP_ACCOUNT_ATTRIBUTE).  I should be able to get it working with that; the main issue is that usernames would have spaces in them.  I'm not sure how well that works with other systems either.

**Comment by Kanshiroron** [comment]
Hey @wheelybird,
Thank you or your answer. After checking, we have no field that contains a space in it, anywhere and especially in the `cn` (only have 2 entries).
And yeah sorry I introduced one in my example with users1's `givenName` & `sn` as this doesn't reflects reality.

**Comment by wheelybird** [comment]
I've started updating the code to cope with using a CN as the account identifier (or whichever attribute people choose).   It might take a few days as I haven't much spare time right now.

**Comment by Kanshiroron** [comment]
Hey @wheelybird 
Thank you for the quick answer. You are actually right, I'm not sure using `cn` as user identifier is a good idea, I'm changing it to `uid` so I shouldn't face this issue any longer.

**Comment by Kanshiroron** [comment]
I confirm that I don't see the error when using `uid` as the `LDAP_ACCOUNT_ATTRIBUTE`

**Comment by wheelybird** [comment]
Adding support to use CN for usernames turned out to be too involved to add.  The posixaccount objectclass requires that UID is set anyway, so it doesn't make much sense to support any other attribute unless I rewrote everything as a generic LDAP editor, and that's not the purpose of this utility.
In fact, I'll update it so that the account attribute is no longer a setting in order to avoid this sort of issue in the future.
