### ISSUE TITLE
php 7.0 is EOL

### ISSUE THREAD

**Issue by galibozek** [wheelybird/ldap-user-manager#80]
Please upgrade base image to minimum php:7.3-apache or newer

**Comment by wheelybird** [comment]
Thanks for this issue.  The next release will be based PHP 8.

**Comment by wheelybird** [comment]
I've pushed a new branch with the next release candidate.  https://github.com/wheelybird/ldap-user-manager/tree/next_release
This now uses PHP 8.  Give it a try and let me know if you have any problems.  The container is available from Docker Hub as wheelybird/ldap-user-manager:next_release
