### ISSUE TITLE
unable to save password as clear text

### ISSUE THREAD

**Issue by lkeijser** [wheelybird/ldap-user-manager#83]
**Check the debugging logs**
Please run the user manager with the debugging settings enabled.  This might help you resolve the issue without needing to create a bug report.   
Set `LDAP_DEBUG` and `LDAP_VERBOSE_CONNECTION_LOGS` to `TRUE` for LDAP issues.   

**Version**
Running the latest version in k8s

**Describe the bug**
I've set PASSWORD_HASH to "CLEAR" and 'env | grep PASSWORD' inside the container confirms it, but somehow LUM won't save the password in cleartext. The openldap I'm using is capable of it though, since in (yuck) phpldapadmin it works fine.

**Comment by wheelybird** [comment]
Hi.  How are you determining that the password isn't in cleartext?  Tools like slapcat and ldapsearch will encode the password (to base64, I think).

**Comment by lkeijser** [comment]
When I do an ldapsearch on the uid I created, the output indeed contains a base64 encoded userPassword field, but when you decode it, it shows {MD5}<string> instead of the just <my-password>.
