### ISSUE TITLE
Cannot send e-mail with credentials to the user - Invalid address

### ISSUE THREAD

**Issue by rbrayner** [wheelybird/ldap-user-manager#85]
First of all, thanks for this awesome project!

**Check the debugging logs**
[Tue Mar 23 03:29:36.824114 2021] [:error] [pid 22] [client 10.164.44.140:33650]  SMTP (level 4): Invalid address:  (to): , referer: https://example.com/account_manager/new_user.php
[Tue Mar 23 03:29:36.824182 2021] [:error] [pid 22] [client 10.164.44.140:33650]  SMTP: Unable to send email: You must provide at least one recipient email address., referer: https://example.com/account_manager/new_user.php

**Version**
v1.6

**Describe the bug**
The SMTP settings seems to be correct, since I can receive e-mails with the ACCOUNT_REQUESTS_ENABLED enabled. That is, the user can request an account and I am receiving the e-mail correctly. Nevertheless, when creating a new account and checking the "Email these credentials to the user?" option, the e-mail is not sent and the following message is displayed (the e-mail address field is being filled with a valid e-mail address):

The account was created but unfortunately the email wasn't sent.
More information will be available in the logs.

The logs were printed above.

The settings:

  - name: SMTP_HOSTNAME
    value: "smtp.office365.com"
  - name: SMTP_HOST_PORT
    value: "587"
  - name: SMTP_USERNAME
    value: "noreply@example.com"
  - name: SMTP_PASSWORD
    value: "password"
  - name: SMTP_USE_TLS
    value: "true"
  - name: EMAIL_FROM_ADDRESS
    value: "noreply@example.com"
  - name: EMAIL_FROM_NAME
    value: "LDAP Manager"
  - name: SMTP_LOG_LEVEL
    value: "4"

**Comment by wheelybird** [comment]
That should be fixed in the `wheelybird/ldap-user-manager:latest` image.  Let me know if not.
