### ISSUE TITLE
empty uniqueMember query Problem

### ISSUE THREAD

**Issue by eishai1** [wheelybird/ldap-user-manager#90]
When creating a group, an "empty uniqueMember" is created.
This empty member causes problems when querying the group members.
Is it possible to remove this "empty uniqueMember"?
Or that this is not created when creating the group?

...
objectClass: top
objectClass: groupOfUniqueNames
objectClass: posixGroup
cn: admins
gidNumber: 2002
**uniqueMember:**
uniqueMember: uid=manager,ou=people
...

Thanks for your effort.

**Comment by wheelybird** [comment]
Hi.  I seem to remember that I wasn't able to create a new group where the uniqueMember attribute was undefined, so I created the empty entry to get around that issue.  I suppose this could be avoided by getting the user to select an initial group member when creating the group.

**Comment by wheelybird** [comment]
I've pushed a new branch with the next release candidate.  https://github.com/wheelybird/ldap-user-manager/tree/next_release
The group creation has changed so there's no empty member entry.  This won't remove any existing entry empty records - you'll need to purge those manually.  Give it a try and let me know if you have any problems.  The container is available from Docker Hub as wheelybird/ldap-user-manager:next_release

**Comment by eishai1** [comment]
Hi, thanks for your help. Now it works correctly when you create a group and assign a user. No empty "uniqueMember" is displayed. The groups can now be read correctly.
