### ISSUE TITLE
Cannot send emails via SMTP

### ISSUE THREAD

**Issue by kevev** [wheelybird/ldap-user-manager#91]
Thank You for the awesome app! It is just what we needed.  :)

Version is current.

Cannot send email via SMTP.

Email provider's recommended settings:

https://docs.rackspace.com/support/how-to/setting-up-a-mail-relay/

Config:
`           -e "SMTP_HOSTNAME=secure.emailsrvr.com" \
           -e "SMTP_HOST_PORT=465" \
           -e "SMTP_USERNAME=private@private.com" \
           -e "SMTP_PASSWORD=private" \
           -e "SMTP_USE_TLS=TRUE" \
           -e "SMTP_LOG_LEVEL=4" \
           -e "EMAIL_FROM_ADDRESS=private@private.com" \
           -e "EMAIL_FROM_NAME=TSP LDAP" \`

LOG:
`[Wed May 12 00:03:29.450930 2021] [:error] [pid 28] [client 172.17.0.1:57406]  LDAP password: using 'SSHA' as the hashing method, referer: https://ldap.texassportsproductions.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:03:29.451021 2021] [:error] [pid 28] [client 172.17.0.1:57406]  password update - algo SSHA | pwd PRIVATE==, referer: https://ldap.texassportsproductions.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:03:29.466160 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP (level 3): Connection: opening to secure.emailsrvr.com:465, timeout=300, options=array(), referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:03:29.475209 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP (level 3): Connection: opened, referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:04:29.544847 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP (level 4): SMTP INBOUND: "", referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:04:29.544896 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP (level 2): SERVER -> CLIENT: , referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:04:29.544942 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP (level 1): SMTP NOTICE: EOF caught while checking if connected, referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:04:29.545037 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP (level 3): Connection: closed, referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:04:29.545208 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP (level 4): SMTP Error: Could not authenticate., referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:04:29.545243 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP (level 4): SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting, referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
[Wed May 12 00:04:29.545250 2021] [:error] [pid 28] [client 172.17.0.1:57406]  SMTP: Unable to send email: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting, referer: https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE
ldap.PRIVATE.com:443 172.17.0.1 - - [12/May/2021:00:03:29 +0000] "POST /account_manager/show_user.php?account_identifier=PRIVATE HTTP/1.1" 200 5889 "https://ldap.PRIVATE.com/account_manager/show_user.php?account_identifier=PRIVATE" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"`

**Comment by wheelybird** [comment]
Hi.  Rackspace uses SMTP over SSL which isn't supported by the user manager.  This will be added in a future update, but there's no timeline for that at the moment.

**Comment by wheelybird** [comment]
I've pushed a new branch with the next release candidate.  https://github.com/wheelybird/ldap-user-manager/tree/next_release
This has the `SMTP_USE_SSL` environmental variable which should allow SMTPS.  I haven't tested it as I haven't got a SMTPS server to test against.  Give it a try and let me know if you have any problems.  The container is available from Docker Hub as wheelybird/ldap-user-manager:next_release
