### ISSUE TITLE
Installation out of docker? on a fresh debian buster container?

### ISSUE THREAD

**Issue by Thatoo** [wheelybird/ldap-user-manager#92]
Hello,

Is it possible to run your promising software out of docker? in a proxmox container, installing on a fresh debian buster container?
Using Nginx or Apache as a web server?
Could you provide an installation guide?

Best regards,

**Comment by wheelybird** [comment]
It's _designed_ to be run as a container.  The quick start guide gives an example:  https://github.com/wheelybird/ldap-user-manager#quick-start
I'm not familiar with Proxmox, but if it supports Docker containers then you're all set.  Apache is embedded in the container, so you don't need to install Apache or Nginx to run it, but if you're talking about using them as a reverse proxy then that's something you'll need to configure yourself.

**Comment by Thatoo** [comment]
Thank you for this very fast answer.
Well, I guess my question is if it could be possible to install it out of a docker container and have an install guide similar to : 
- apt install DEPENDENCIES
- wget https://URL_to_download_install_LUM_folder
- cp LUM /var/www/LUM
- cp LUM/apache2LUM.conf /etc/apache2/sites-available/apache2LUM.conf
- ln -s /etc/apache2/sites-enable/apache2LUM.conf /etc/apache2/sites-available/apache2LUM.conf
- service apache2 reload

That would be awesome!

**Comment by wheelybird** [comment]
Sorry, I misread your original question.  To run outside of a container you can copy the Apache config that the entrypoint generates (https://github.com/wheelybird/ldap-user-manager/blob/65bee01fadd2a0a5d07c8f8e7ae3402c725d27ac/entrypoint#L108) and, as you say, copy the `www/` directory to the DocumentRoot.  To pass in configuration you need to set environmental variables that Apache can access.  If your distribution has an `/etc/apache2/envvars` file then that's a good place to put them.  Alternatively you can put them in the VirtualHost configuration by using `SetEnv VARIABLE_NAME variable_value` directives.

**Comment by Thatoo** [comment]
Any dependencies to install?
php of course
maybe some php module like php-ldap php-zip php-curl ...?

And then I guess with this list it will be good to go.
Thank you

I'll take notes and if I succeed I'll drop it here as a tuto for others.

**Comment by wheelybird** [comment]
The dependencies are shown in the Dockerfile: https://github.com/wheelybird/ldap-user-manager/blob/master/Dockerfile
If you're using a non-Debian distribution then you'll need to find the equivalent package names.  You'll need the PHP GD library and the LDAP library.  Your distribution might offer those as packages.

**Comment by Thatoo** [comment]
Here is the script I have written to install  LDAP User Manager with nginx web server on Debian 10
https://github.com/Thatoo/ldap-user-manager/blob/master/install-debian-nginx.sh

With a minor modification, it can work out of the box at the root of a domain.
However, I wanted to increase security and wanted the default nginx page to display at the root of the domain (to make bot think that there is nothing to look for) and wanted LDAP User Manager to display on a subfolder that I decide like http://URL/ldap-user-manager .
To do that, I had to make a modification of your code because it has not taken in account the will to work in a subdirectory
https://github.com/Thatoo/ldap-user-manager/commit/a60c3bda161bc776b193aef9bcf3c32e98533a65#diff-68a345129d5e167a94a22281827e0d47ce4aa0955a1c04cb610602b53912cc35
I know this modification is not ideal because I force https but I couldn't make it work with $SITE_PROTOCOL .
For some reason $_SERVER["HTTP_HOST"] include a / at its beginning which cause trouble...

Could you help?

**Comment by Thatoo** [comment]
By the way, I could make it work behind a reverse proxy nginx too...

**Comment by Thatoo** [comment]
it would be nice to have an environmental variables for subfolder empty by default and change  
        print "<a href='/{$module}/'>$this_module_name</a></li>\n";
by something like
        print "<a href=" . $SUBFOLDER . /{$module}/>$this_module_name</a></li>\n";

I'm not so sure how to make it simple...

**Comment by Thatoo** [comment]
I have updated my install script. It works for someone who want to install at the root of his/her domain but not fully for someone who want to install in a subfolder of the domain yet because LUM doesn't provide this possibility yet.
