### ISSUE TITLE
LUM behind a reverse proxy nginx?

### ISSUE THREAD

**Issue by Thatoo** [wheelybird/ldap-user-manager#93]
Hello,

Is it possible to run LUM on a container behind a reverse proxy nginx (in an other container)?
How to adapt LUM to run behind such classical reverse proxy nginx conf?

```
server {
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://xxx.xxx.xxx.xxx;      # xxx.xxx.xxx.xxx being the local IP adresse of the LUM container
    }
    server_name URL_OF_LUM;
    server_tokens off;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/URL_OF_LUM/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/URL_OF_LUM/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff;

}

server {
    if ($host = URL_OF_LUM) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name URL_OF_LUM;
    listen [::]:80;
    listen 80;
    return 404; # managed by Certbot
}

```

Setting LUM with the option
"NO_HTTPS=TRUE"
wil it be enough?

**Comment by wheelybird** [comment]
I'm not an Nginx expert so I can't advise on how to set this up.  In theory it should be no different to setting up Nginx to reverse-proxy to any other service.  You shouldn't need to disable HTTPS either - Nginx ought to have no problem with the self-signed certificate.

**Comment by Thatoo** [comment]
Well, the reverse proxy only is getting let'sencrypt certificate because port 80 and 443 are redirected to it (from public IP).
Then, I have never seen https being used between the reverse proxy and a local container.
It's always 
proxy_pass http://xxx.xxx.xxx.xxx;
and not
proxy_pass https://xxx.xxx.xxx.xxx;

In my experience with other software that could be running behind reverse proxy like Nextcloud, Jitsi, Dolibarr... all conf we can find are with  proxy_pass http://xxx.xxx.xxx.xxx; . It's of course always mention to do that only on a secure local network. This way, HTTPS is not really needed as exchange are between local IPs (behind firewall, NAT whatever).

**Comment by Thatoo** [comment]
I could make it work behind a nginx reverse proxy with a let'sencrypt certificate but I need to improve this very basic nginx conf

```
server {
    location / {
        include proxy_params;
        proxy_pass http://xxx.xxx.xxx.xxx;
    }
    server_name URL.com;
#    server_tokens off;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/URL.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/URL.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = URL.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name URL.com;
    listen [::]:80;
    listen 80;
    return 404; # managed by Certbot
}
```
