### ISSUE TITLE
Subfolder

### ISSUE THREAD

**Issue by Thatoo** [wheelybird/ldap-user-manager#94]
Could it be possible to install LUM in a subfolder to get access to it at https://url.com/subfolder and not necessarily at https://url.com ?

For instance, the login button redirect necessarily to https://url.com/log_in and not to https://url.com/subfolder/log_in ?

**Comment by Thatoo** [comment]
It could be something like
We'd add an optional environmental variables for subfolder (subfolder), empty by default and change
print "<a href='/{$module}/'>$this_module_name</a></li>\n";
by something like
print "<a href=/" . $SUBFOLDER . /{$module}/>$this_module_name</a></li>\n";

**Comment by Thatoo** [comment]
I have find a way. Please, let me know what you think about it

In web_functions.inc.php, I added
`$ROOT_SITE = $SITE_PROTOCOL . $_SERVER["HTTP_HOST"];`

just below 

```
if (isset($_SERVER['HTTPS']) and
   ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) or
   isset($_SERVER['HTTP_X_FORWARDED_PROTO']) and
   $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
  $SITE_PROTOCOL = 'https://';
}
else {
  $SITE_PROTOCOL = 'http://';
}
```

and then, in the render_menu() , I added $ROOT_SITE like that

` global $ROOT_SITE, $SITE_NAME, $MODULES, $THIS_MODULE_PATH, $VALIDATED, $IS_ADMIN, $USER_ID;`

and

`       print "<a href=" . $ROOT_SITE . "/{$module}>$this_module_name</a></li>\n";`

It works for me!

The thing is that I guess we need to change everywhere you had wrote a relative path.

**Comment by Thatoo** [comment]
Did you have many relative path like this one? I did not find other...
In that case, I could make such PR to allow people to work in subfolder if they want.

**Comment by Thatoo** [comment]
I had to update run_checks.php at the line 25
from
  <form action="<?php print "$/$THIS_MODULE_PATH/setup_ldap.php"; ?>" method="post">
to
  <form action="<?php print "$ROOT_SITE/$THIS_MODULE_PATH/setup_ldap.php"; ?>" method="post">

**Comment by Thatoo** [comment]
and also new_user.php 
line 17 from
 $completed_action="/log_in";
to
 $completed_action="$ROOT_SITE/log_in";
and line 26 from
 $completed_action="/$THIS_MODULE_PATH/";
to
 $completed_action="$ROOT_SITE/$THIS_MODULE_PATH/";

**Comment by Thatoo** [comment]
I guess it's going to be long to do all especially that now I encounter an other problem
in new_user.php , line 220, 226 and 227,
`<script type="text/javascript" src="/js/zxcvbn-bootstrap-strength-meter.js"></script>`
would also need to be changed with
`<script type="text/javascript" src="$SUBFOLDER/js/zxcvbn-bootstrap-strength-meter.js"></script>`
$SUBFOLDER being different than $ROOT_SITE

Maybe some day, I'll have energy to go till the end but for now, I don't recommend trying to use my script on a subfolder.

**Comment by Thatoo** [comment]
To continue, I'd need at least your help to create this new environmental variables in config.inc.php like those : 

```
 $SITE_NAME = (getenv('SITE_NAME') ? getenv('SITE_NAME') : "$ORGANISATION_NAME user manager");
 $SERVER_HOSTNAME = (getenv('SERVER_HOSTNAME') ? getenv('SERVER_HOSTNAME') : "ldapusermanager.org");
```

something like

$SUBFOLDER = (getenv('HTTP_SUBFOLDER') ? getenv('HTTP_SUBFOLDER') .......

**Comment by Thatoo** [comment]
I think I went all around to add
$ROOT_SITE before all $THIS_MODULE_PATH that needed it
and add
$SUBFOLDER to all src="... that needed it

but to make it working, I just need to be able to set a value to SUBFOLDER with the help of a new environmental variables in config.inc.php .
Could you help me with that?
With your help, I'll complete my fork : https://github.com/Thatoo/ldap-user-manager

I'll do some test before creating a PR.

Hope you'll agrre with my work.
Regards,

**Comment by Thatoo** [comment]
Actually I manage to do something about this new environmental variables.

My only problem remaining is when I go to /account_manager/index.php or account_manager/groups.php
and I want to add a new user or a new group, then, I get a 404 error because the URL it tries to go to is
account_manager/NAN/new_user.php
or
account_manager/NAN/show_group.php

instead of 
account_manager/new_user.php
or
account_manager/show_group.php

Where does this NAN coming from, I don't know but if I solve that, then I guess it will be good for complete review before a PR.

**Comment by Thatoo** [comment]
I got it. Instead of
`  <form action="<?php print $ROOT_SITE/$THIS_MODULE_PATH; ?>/show_group.php" method="post">`
it should be
`  <form action="/$SUBFOLDER/<?php print $THIS_MODULE_PATH; ?>/show_group.php" method="post">`

It makes me realize that I might not need $ROOT_SITE at all, but only $SUBFOLDER...
I should check on that.
Anyway, I guess it's working now.
I'll make some test before making further changes and ask for review.

**Comment by Thatoo** [comment]
@wheelybird : I've just made a PR.
If you merge it, then this Issue and the two others I have opened could be closed.

**Comment by wheelybird** [comment]
Hi.  This issue was also raised here:  https://github.com/wheelybird/ldap-user-manager/issues/81
I've already updated the code to address this issue which will be included with the next release.  Unfortunately I haven't had any time recently to continue working on the next release.

**Comment by Thatoo** [comment]
Well, hopefully my work can help you

**Comment by Thatoo** [comment]
I can't wait to see your code to compare with mine and learn :-)

**Comment by wheelybird** [comment]
I've pushed a new branch with the next release candidate.  https://github.com/wheelybird/ldap-user-manager/tree/next_release
This has the `SERVER_PATH` environmental variable which will set the path to the user manager.  Give that a try and let me know if you have any problems.

**Comment by Thatoo** [comment]
It seems to work but only if I define the SERVER_PATH variable to "/SUBFOLDER" and not to "SUBFOLDER like that
```
fastcgi_param   HTTP_HOST       URL;
fastcgi_param   SERVER_PATH        /subfolder;
```
if I simply do
```
fastcgi_param   HTTP_HOST       URL;
fastcgi_param   SERVER_PATH        subfolder;
```
It doesn't work.

If I change in /var/www/html/brigade/includes/web_functions.inc.php line 36
` if (substr($SERVER_PATH, -1) != "/") { $SERVER_PATH .= "/"; }`
into
`if (substr($SERVER_PATH, -1) != "/") { $SERVER_PATH = "/" . $SERVER_PATH . "/"; }`
it almost worked.

I had an error going to setup/${SERVER_PATH}setup/run_checks.php?

**Comment by Thatoo** [comment]
let me know when you update your code and I'll test it again

**Comment by wheelybird** [comment]
Hi.  The code isn't wrong - this is intentional.  The default is `/`.  https://github.com/wheelybird/ldap-user-manager/tree/next_release#organisation-settings
What's exactly is the problem with setting your path to `/whatever`?

**Comment by Thatoo** [comment]
Nothing, just weird. I didn't say the code is wrong.
Both are working I guess, either
` if (substr($SERVER_PATH, -1) != "/") { $SERVER_PATH = "/" . $SERVER_PATH . "/"; }`
and people shoudl write /subfolder in their `SERVER_PATH` variable 
either
` if (substr($SERVER_PATH, -1) != "/") { $SERVER_PATH .= "/"; }`
and people could simply write subfolder in their `SERVER_PATH` variable

It's a choice. It doesn't affect default being `/` (and I agree it should be `/` as default)

**Comment by Thatoo** [comment]
About setup_ldap.php line 189
` <form action="${SERVER_PATH}setup/run_checks.php">`
it should wotk?
It doesn't unfortunately no matter if I keep 
` if (substr($SERVER_PATH, -1) != "/") { $SERVER_PATH .= "/"; } `
with `/subfolder` in my `SERVER_PATH` variable
or If I change it to
` if (substr($SERVER_PATH, -1) != "/") { $SERVER_PATH .= "/"; }`
`subfolder` in my `SERVER_PATH` variable

**Comment by Thatoo** [comment]
In setup_ldap.php line 141 it is
`  <form action="<?php print "${SERVER_PATH}account_manager/new_user.php"; ?>" method="post">`
and it works
but line 189
` <form action="${SERVER_PATH}setup/run_checks.php">`
doesn't work. To make it work, I need to change it to a similar way than line 141
` <form action="<?php print ${SERVER_PATH}; ?>setup/run_checks.php">`
I guess it would be coherent also to change line 170 from
`  <form action="${SERVER_PATH}">`
to
`  <form action="<?php print ${SERVER_PATH}; ?>`

**Comment by wheelybird** [comment]
Yeah, that need fixing.  I'll sort that out and push to the `next_release` branch when I can.

**Comment by Thatoo** [comment]
I look at the code and I think that's the only thing to change.

**Comment by Thatoo** [comment]
it works on next_release branch!
