### ISSUE TITLE
memberOf not populating when adding user to group

### ISSUE THREAD

**Issue by kevev** [wheelybird/ldap-user-manager#95]
I am using: --env LDAP_RFC2307BIS_SCHEMA=true \

But when I add a new user to a group, the user does not have the memberOf attribute.

Not sure what I am missing here. Any ideas? Thanks in advance. :)

https://imgur.com/a/qepDoRj

**Comment by kevev** [comment]
My bad. memberOf is actually there. Generic ldapsearc does not show that attribute. slapcat does.

docker exec IMAGEID slapcat

**Comment by Thatoo** [comment]
Well, I do have the same issue but slapcat doesn't show me any memberOf neither.
I alsoi have this sentence : 

    ☑ The RFC2307BIS schema appears to be available. What's this?

Nextcloud don't find any memberOf neither. It is saying : Groups are disabled because the LDAP / AD server does not support memberOf.
I don't understand because 
```
$ ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b  cn=config olcDatabase | grep mdb
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
dn: olcBackend={0}mdb,cn=config
dn: olcDatabase={1}mdb,cn=config
olcDatabase: {1}mdb
dn: olcOverlay={0}memberof,olcDatabase={1}mdb,cn=config
```
and
 ```
$ ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b  cn=config -LLL | grep -i module
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
dn: cn=module{0},cn=config
objectClass: olcModuleList
cn: module{0}
olcModulePath: /usr/lib/ldap
olcModuleLoad: {0}back_mdb
olcModuleLoad: {1}memberof.la
olcModuleLoad: {2}refint.la
olcAttributeTypes: ( OLcfgGlAt:30 NAME 'olcModuleLoad' EQUALITY caseIgnoreMatc
olcAttributeTypes: ( OLcfgGlAt:31 NAME 'olcModulePath' SYNTAX OMsDirectoryStri
olcObjectClasses: ( OLcfgGlOc:8 NAME 'olcModuleList' DESC 'OpenLDAP dynamic mo
 dule info' SUP olcConfig STRUCTURAL MAY ( cn $ olcModulePath $ olcModuleLoad 
```

Any help is welcomed...

**Comment by Thatoo** [comment]
My bad, I had configure memberof for groupOfNames but LUM use groupOfUniqueNames. It works now!
