### ISSUE TITLE
Feature Request: Allow redefining uidNumber, other 'default attributes' as an enter-able field

### ISSUE THREAD

**Issue by dcacklam** [wheelybird/ldap-user-manager#97]
Presently if I include 'uidNumber' in the list of additional attributes, LUM throws an error for a duplicate attribute.

It would be more useful, if the values entered in 'Additional Attributes' overrode these values, such that you could re-label attributes or make them into enter-able fields....

Eg, if 'uidNumber' and 'gidNumber' were defined in additional_attributes, then the $account_attributes array would look like this:

$account_attributes = array('objectClass' => $objectclasses,                                                                                                                                     'displayName' => $account_r['givenname'] . " " . $account_r['sn'],                                                                                                   'loginShell' => $DEFAULT_USER_SHELL,                                                                                                                                 'homeDirectory' => "/home/" . $account_r['uid'],                                                                                                                     'userPassword' => $hashed_pass,                                                                                                                            );      

If they were not, it would look normal.

**Comment by wheelybird** [comment]
Thanks for reporting this.  I thought I'd written it so you could override, but evidently not.  I'll take a look.

**Comment by dcacklam** [comment]
I sent you a short PR to fix it.

**Comment by wheelybird** [comment]
Thanks for the PR, but I'd already updated the code.  I've just pushed the changes to the next_release branch and updated the `wheelybird/ldap-user-manager:next_release` container.
