### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by eduardhc** [wheelybird/ldap-user-manager#99]
Would it possible to be able to use this LDAP user manager in an offline environment? The product runs great, and provides a very nice and clean interface for managing a simple LDAP setup such as ours.

However, in this particular case both the LDAP server and the LDAP frontend need to run in an offline environment, with no internet access, for security restrictions. For what I've seen, in such an environment the frontend fails to run properly as it attempts to download some JS APIs and packages from the internet.

Any chance of this being usable on a secured offline environment?

**Comment by wheelybird** [comment]
Yes, that's not a problem.  I'll add that into the next release.

**Comment by eduardhc** [comment]
Great, thanks! Any estimation on when the version will be available?
